
package com.rndash.mbheadunit.nativeCan.canC

import com.rndash.mbheadunit.nativeCan.CanBusNative // AUTO GEN

/**
 *   Generated by db_converter.py
 *   Object for AAD_580h (ID 0x0580)
**/

object AAD_580h {

    	/** Gets code number acceleration type (> 100: dynamic) **/
	fun get_ftk_bmi() : Int = CanBusNative.getECUParameterC(CanCAddrs.AAD_580h, 0, 8)
	
	/** Gets Code number for lateral acceleration type (> 100: dynamic) **/
	fun get_ftk_lmi() : Int = CanBusNative.getECUParameterC(CanCAddrs.AAD_580h, 8, 8)
	
	/** Gets code number brake type (> 100: dynamic) **/
	fun get_ftk_vmi() : Int = CanBusNative.getECUParameterC(CanCAddrs.AAD_580h, 16, 8)
	
	/** Gets Max.diff. Pedal angle value per maneuver **/
	fun get_ftk_dpw() : Int = CanBusNative.getECUParameterC(CanCAddrs.AAD_580h, 32, 8)
	
	/** Gets Continuous driver observation **/
	fun get_aadkb() : Int = CanBusNative.getECUParameterC(CanCAddrs.AAD_580h, 40, 8)
	
	/** Gets Spontaneous dynamic demand **/
	fun get_aadkbdyn() : Boolean = CanBusNative.getECUParameterC(CanCAddrs.AAD_580h, 48, 1) != 0
	
	/** Gets Nervousness **/
	fun get_aadnt() : Int = CanBusNative.getECUParameterC(CanCAddrs.AAD_580h, 56, 8)
	
	
}
