
package com.rndash.mbheadunit.nativeCan.canC

import com.rndash.mbheadunit.nativeCan.CanBusNative // AUTO GEN

/**
 *   Generated by db_converter.py
 *   Object for ARCADE_A2 (ID 0x0035)
**/

object ARCADE_A2 {

    	/** Gets frontal event 5 **/
	fun get_crash_c() : Boolean = CanBusNative.getECUParameterC(CanCAddrs.ARCADE_A2, 5, 1) != 0
	
	/** Gets frontal event 2 **/
	fun get_crash_f() : Boolean = CanBusNative.getECUParameterC(CanCAddrs.ARCADE_A2, 2, 1) != 0
	
	/** Gets Confirm bit for all crash events, toggling **/
	fun get_conf_crash() : Boolean = CanBusNative.getECUParameterC(CanCAddrs.ARCADE_A2, 0, 1) != 0
	
	
}
