
@file:Suppress("unused", "FunctionName", "ClassName")
package com.rndash.mbheadunit.nativeCan.canC
import com.rndash.mbheadunit.CanFrame // AUTO GEN
import com.rndash.mbheadunit.nativeCan.CanBusNative // AUTO GEN

/**
 *   Generated by db_converter.py
 *   Object for BS_270h (ID 0x0270)
**/

object BS_270h {

    /** 
     *  Returns the most recent Can Frame representing the state
     *  of BS_270h
    **/
    fun get_frame() : CanFrame? = CanBusNative.getCFrame(CanCAddrs.BS_270h)

	/** Gets Pulse ring counter, rear left wheel (48 per revolution) **/
	fun get_riz_hl() : Int = CanBusNative.getECUParameterC(CanCAddrs.BS_270h, 0, 8)
	
	/** Sets Pulse ring counter, rear left wheel (48 per revolution) **/
	fun set_riz_hl(f: CanFrame, p: Int) : CanFrame? {
		checkFrame(f)
		return CanBusNative.setFrameParameter(f, 0, 8, p)
	}
	
	/** Gets Pulse ring counter, rear right wheel (48 per revolution) **/
	fun get_riz_hr() : Int = CanBusNative.getECUParameterC(CanCAddrs.BS_270h, 8, 8)
	
	/** Sets Pulse ring counter, rear right wheel (48 per revolution) **/
	fun set_riz_hr(f: CanFrame, p: Int) : CanFrame? {
		checkFrame(f)
		return CanBusNative.setFrameParameter(f, 8, 8, p)
	}
	
	/** Gets Flat roll warning status **/
	fun get_prw_st() : PRW_ST = when(CanBusNative.getECUParameterC(CanCAddrs.BS_270h, 21, 3)) {
		 0 -> PRW_ST.ON
		 1 -> PRW_ST.WARN
		 2 -> PRW_ST.OFF
		 3 -> PRW_ST.INIT
		 4 -> PRW_ST.NOT_DEFINED
		 5 -> PRW_ST.NOT_DEFINED_5
		 6 -> PRW_ST.PRW_NV
		 7 -> PRW_ST.SNV
		 else -> throw Exception("Invalid raw value for PRW_ST")
	}
	
	/** Sets Flat roll warning status **/
	fun set_prw_st(f: CanFrame, p: PRW_ST) : CanFrame? {
		checkFrame(f)
		return CanBusNative.setFrameParameter(f, 21, 3, p.raw)
	}
	
	/** Gets Warning messages flat roll warner **/
	fun get_prw_warn() : PRW_WARN = when(CanBusNative.getECUParameterC(CanCAddrs.BS_270h, 16, 4)) {
		 0 -> PRW_WARN.OK
		 1 -> PRW_WARN.WARN_OHNE
		 2 -> PRW_WARN.PRW_NV
		 3 -> PRW_WARN.PRW_START
		 4 -> PRW_WARN.WARN_VL
		 5 -> PRW_WARN.WARN_VR
		 6 -> PRW_WARN.WARN_HL
		 7 -> PRW_WARN.WARN_HR
		 8 -> PRW_WARN.NOT_DEFINED
		 14 -> PRW_WARN.UNDEFINED
		 15 -> PRW_WARN.SNV
		 else -> throw Exception("Invalid raw value for PRW_WARN")
	}
	
	/** Sets Warning messages flat roll warner **/
	fun set_prw_warn(f: CanFrame, p: PRW_WARN) : CanFrame? {
		checkFrame(f)
		return CanBusNative.setFrameParameter(f, 16, 4, p.raw)
	}
	
	/**
     * Auto generated function
     * Throws exception if user tries to set a value in a frame
     * Not designated from the correct ECU
    **/
    private fun checkFrame(f: CanFrame) {
        if (f.canID != CanCAddrs.BS_270h.addr) {
            throw IllegalArgumentException("CAN ID does not match object!")
        }
    }

	override fun toString() = """
		|Pulse ring counter, rear left wheel (48 per revolution): ${get_riz_hl()}
		|Pulse ring counter, rear right wheel (48 per revolution): ${get_riz_hr()}
		|Flat roll warning status: ${get_prw_st()}
		|Warning messages flat roll warner: ${get_prw_warn()}
	""".trimMargin("|")
}
