package com.rndash.mbheadunit.nativeCan.canC


import com.rndash.mbheadunit.nativeCan.CanCAddrs
import com.rndash.mbheadunit.nativeCan.CanBusNative



/**
 *    GENERATED BY parse_kt.py
 *    Decoder class for ECU Frame BS_300h (ID: 0x0300)
**/
object BS_300h {

	/** Engine torque request parity (even parity) **/
	fun get_dmpar_art() : Boolean = getParam(0, 1) != 0

	/** Engine torque request Dynamic **/
	fun get_dmdyn_art() : Boolean = getParam(1, 1) != 0

	/** BAS control active **/
	fun get_bas_akt() : Boolean = getParam(2, 1) != 0

	/** Emergency braking (ABS controls all 4 wheels) **/
	fun get_vollbre() : Boolean = getParam(3, 1) != 0

	/** Enable ART **/
	fun get_art_e() : Boolean = getParam(4, 1) != 0

	/** ESP yaw moment control is active **/
	fun get_esp_gier_akt() : Boolean = getParam(5, 1) != 0

	/** Initialization steering angle sensor O.K. **/
	fun get_lws_ini_ok() : Boolean = getParam(6, 1) != 0

	/** Initialization steering angle sensor possible **/
	fun get_lws_ini_ein() : Boolean = getParam(7, 1) != 0

	/** Engine torque request parity (even parity) **/
	fun get_mpar_esp() : Boolean = getParam(8, 1) != 0

	/** Engine torque request Dynamic **/
	fun get_mdyn_esp() : Boolean = getParam(9, 1) != 0

	/** Drive torque control active **/
	fun get_amr_akt_esp() : Boolean = getParam(10, 1) != 0

	/** Cycle time **/
	fun get_t_z() : Int = getParam(11, 2)

	/** Driver brakes parity (even parity) **/
	fun get_sfb_pa() : Boolean = getParam(13, 1) != 0

	/** driver brakes **/
	fun get_sfb() : Int = getParam(14, 2)

	/** Motormomentenanf. Toggle 40ms + -10 **/
	fun get_dmtgl_art() : Boolean = getParam(16, 1) != 0

	/** Engine torque requirement Min **/
	fun get_dmmin_art() : Boolean = getParam(17, 1) != 0

	/** Engine torque requirement Max **/
	fun get_dmmax_art() : Boolean = getParam(18, 1) != 0

	/** Geford. engine torque **/
	fun get_dm_art() : Int = getParam(19, 13)

	/** Motormomentenanf. Toggle 40ms + -10 **/
	fun get_mtgl_esp() : Boolean = getParam(32, 1) != 0

	/** Engine torque requirement Min **/
	fun get_mmin_esp() : Boolean = getParam(33, 1) != 0

	/** Engine torque requirement Max **/
	fun get_mmax_esp() : Boolean = getParam(34, 1) != 0

	/** Geford. engine torque **/
	fun get_m_esp() : Int = getParam(35, 13)

	/** Raw signal yaw rate without adjustment / filtration (+ = left) **/
	fun get_gier_roh() : Int = getParam(48, 16)

	override fun toString(): String {
		return """
			DMPAR_ART: ${get_dmpar_art()}
			DMDYN_ART: ${get_dmdyn_art()}
			BAS_AKT: ${get_bas_akt()}
			VOLLBRE: ${get_vollbre()}
			ART_E: ${get_art_e()}
			ESP_GIER_AKT: ${get_esp_gier_akt()}
			LWS_INI_OK: ${get_lws_ini_ok()}
			LWS_INI_EIN: ${get_lws_ini_ein()}
			MPAR_ESP: ${get_mpar_esp()}
			MDYN_ESP: ${get_mdyn_esp()}
			AMR_AKT_ESP: ${get_amr_akt_esp()}
			T_Z: ${get_t_z()}
			SFB_PA: ${get_sfb_pa()}
			SFB: ${get_sfb()}
			DMTGL_ART: ${get_dmtgl_art()}
			DMMIN_ART: ${get_dmmin_art()}
			DMMAX_ART: ${get_dmmax_art()}
			DM_ART: ${get_dm_art()}
			MTGL_ESP: ${get_mtgl_esp()}
			MMIN_ESP: ${get_mmin_esp()}
			MMAX_ESP: ${get_mmax_esp()}
			M_ESP: ${get_m_esp()}
			GIER_ROH: ${get_gier_roh()}
		""".trimIndent()
	}


	private fun getParam(o: Int, l: Int) : Int = CanBusNative.getECUParameterC(CanCAddrs.BS_300h, o, l)
}
