package com.rndash.mbheadunit.nativeCan.canC


import com.rndash.mbheadunit.nativeCan.CanCAddrs
import com.rndash.mbheadunit.nativeCan.CanBusNative



/**
 *    GENERATED BY parse_kt.py
 *    Decoder class for ECU Frame DG_RQ_OBD (ID: 0x07DF)
**/
object DG_RQ_OBD {

	/** KWP2000 Diagnose-Request **/
	fun get_d_rq() : Int = getParam(0, 64)

	override fun toString(): String {
		return """
			D_RQ: ${get_d_rq()}
		""".trimIndent()
	}


	private fun getParam(o: Int, l: Int) : Int = CanBusNative.getECUParameterC(CanCAddrs.DG_RQ_OBD, o, l)
}
