
@file:Suppress("unused", "FunctionName")
package com.rndash.mbheadunit.nativeCan.canC
import com.rndash.mbheadunit.CanFrame // AUTO GEN
import com.rndash.mbheadunit.nativeCan.CanBusNative // AUTO GEN

/**
 *   Generated by db_converter.py
 *   Object for EWM_104h (ID 0x0104)
**/

object EWM_104h {

    	/** Gets FBS message to EZS (8 bytes) **/
	fun get_ewm_fbs() : Int = CanBusNative.getECUParameterC(CanCAddrs.EWM_104h, 0, 64)
	
	/** Sets FBS message to EZS (8 bytes) **/
	fun set_ewm_fbs(f: CanFrame, p: Int) = CanBusNative.setFrameParameter(f, 0, 64, p)
	
	
}
