package com.rndash.mbheadunit.nativeCan.canC


import com.rndash.mbheadunit.nativeCan.CanCAddrs
import com.rndash.mbheadunit.nativeCan.CanBusNative



/**
 *    GENERATED BY parse_kt.py
 *    Decoder class for ECU Frame EWM_MESS2 (ID: 0x06F1)
**/
object EWM_MESS2 {

	/** Messwerte **/
	fun get_mess2() : Int = getParam(0, 64)

	override fun toString(): String {
		return """
			MESS2: ${get_mess2()}
		""".trimIndent()
	}


	private fun getParam(o: Int, l: Int) : Int = CanBusNative.getECUParameterC(CanCAddrs.EWM_MESS2, o, l)
}
