package com.rndash.mbheadunit.nativeCan.canC


import com.rndash.mbheadunit.nativeCan.CanCAddrs
import com.rndash.mbheadunit.nativeCan.CanBusNative



/**
 *    GENERATED BY parse_kt.py
 *    Decoder class for ECU Frame EWM_MESS1 (ID: 0x06F0)
**/
object EWM_MESS1 {

	/** Messwerte **/
	fun get_mess1() : Int = getParam(0, 64)

	override fun toString(): String {
		return """
			MESS1: ${get_mess1()}
		""".trimIndent()
	}


	private fun getParam(o: Int, l: Int) : Int = CanBusNative.getECUParameterC(CanCAddrs.EWM_MESS1, o, l)
}
