package com.rndash.mbheadunit.nativeCan.canC


import com.rndash.mbheadunit.nativeCan.CanCAddrs
import com.rndash.mbheadunit.nativeCan.CanBusNative



/**
 *    GENERATED BY parse_kt.py
 *    Decoder class for ECU Frame EZS_240h (ID: 0x0240)
**/
object EZS_240h {

	/** Cruise control lever implausible **/
	fun get_wh_up() : Boolean = getParam(2, 1) != 0

	/** Operation variable speed limit **/
	fun get_vmax_akt() : Boolean = getParam(3, 1) != 0

	/** Cruise control lever: "Sit and delay Stufe0" **/
	fun get_s_minus_b() : Boolean = getParam(4, 1) != 0

	/** Cruise control lever: "Sit and accelerating Stufe0" **/
	fun get_s_plus_b() : Boolean = getParam(5, 1) != 0

	/** Cruise control lever: "resume" **/
	fun get_wa() : Boolean = getParam(6, 1) != 0

	/** Cruise control lever "off" **/
	fun get_aus() : Boolean = getParam(7, 1) != 0

	/** Keyless Go terminal control active **/
	fun get_kg_kl_akt() : Boolean = getParam(8, 1) != 0

	/** Keyles Go annealing conditions met **/
	fun get_kg_alb_ok() : Boolean = getParam(9, 1) != 0

	/** LHD / RHD **/
	fun get_ll_rlc() : Int = getParam(10, 2)

	/** engaged reverse gear (manual transmission only) **/
	fun get_rg_schalt() : Boolean = getParam(12, 1) != 0

	/** Brake switch for Shift Lock **/
	fun get_bs_sl() : Boolean = getParam(13, 1) != 0

	/** terminal 15 **/
	fun get_kl_15() : Boolean = getParam(14, 1) != 0

	/** terminal 50 **/
	fun get_kl_50() : Boolean = getParam(15, 1) != 0

	/** Cruise control lever parity (even parity) **/
	fun get_wh_pa() : Boolean = getParam(19, 1) != 0

	/** message count **/
	fun get_bz240h() : Int = getParam(20, 4)

	/** ASG Sport mode on / off operated (ST2_LED_DL when ABC available) **/
	fun get_asg_sport_bet() : Boolean = getParam(27, 1) != 0

	/** CRASH Confirmbit **/
	fun get_crash_cnf() : Boolean = getParam(30, 1) != 0

	/** Crash signal from airbag SG **/
	fun get_crash() : Boolean = getParam(31, 1) != 0

	/** Wiring emergency: Prio1- and Prio2-consumers, Second battery supports **/
	fun get_bn_ntlf() : Boolean = getParam(32, 1) != 0

	/** ESP operated on / off **/
	fun get_esp_bet() : Int = getParam(33, 2)

	/** Hand brake applied (control light) **/
	fun get_has_kl() : Boolean = getParam(35, 1) != 0

	/** Wiper outside parking position **/
	fun get_kl_31b() : Boolean = getParam(36, 1) != 0

	/** Directional blinking right **/
	fun get_bli_re() : Boolean = getParam(38, 1) != 0

	/** Directional blinking left **/
	fun get_bli_li() : Boolean = getParam(39, 1) != 0

	/** LF / ABC 2-stage switch actuated **/
	fun get_st2_bet() : Int = getParam(40, 2)

	/** LF / ABC 3-position switch is actuated **/
	fun get_st3_bet() : Int = getParam(42, 2)

	/** ART-distance warning actuated on / off **/
	fun get_art_abw_bet() : Int = getParam(44, 2)

	/** switch on low beam **/
	fun get_abl_ein() : Boolean = getParam(46, 1) != 0

	/** Terminal 54 Hardware enabled **/
	fun get_kl54_rm() : Boolean = getParam(47, 1) != 0

	/** distance factor **/
	fun get_art_abstand() : Int = getParam(48, 8)

	/** ART available **/
	fun get_art_vh() : Boolean = getParam(56, 1) != 0

	/** E-extractor: basic ventilation from **/
	fun get_gbl_aus() : Boolean = getParam(57, 1) != 0

	/** Series addicts vehicle version (only 220/215/230) **/
	fun get_fzgversn() : Int = getParam(59, 3)

	/** country code **/
	fun get_ldc() : Int = getParam(62, 2)

	override fun toString(): String {
		return """
			WH_UP: ${get_wh_up()}
			VMAX_AKT: ${get_vmax_akt()}
			S_MINUS_B: ${get_s_minus_b()}
			S_PLUS_B: ${get_s_plus_b()}
			WA: ${get_wa()}
			AUS: ${get_aus()}
			KG_KL_AKT: ${get_kg_kl_akt()}
			KG_ALB_OK: ${get_kg_alb_ok()}
			LL_RLC: ${get_ll_rlc()}
			RG_SCHALT: ${get_rg_schalt()}
			BS_SL: ${get_bs_sl()}
			KL_15: ${get_kl_15()}
			KL_50: ${get_kl_50()}
			WH_PA: ${get_wh_pa()}
			BZ240h: ${get_bz240h()}
			ASG_SPORT_BET: ${get_asg_sport_bet()}
			CRASH_CNF: ${get_crash_cnf()}
			CRASH: ${get_crash()}
			BN_NTLF: ${get_bn_ntlf()}
			ESP_BET: ${get_esp_bet()}
			HAS_KL: ${get_has_kl()}
			KL_31B: ${get_kl_31b()}
			BLI_RE: ${get_bli_re()}
			BLI_LI: ${get_bli_li()}
			ST2_BET: ${get_st2_bet()}
			ST3_BET: ${get_st3_bet()}
			ART_ABW_BET: ${get_art_abw_bet()}
			ABL_EIN: ${get_abl_ein()}
			KL54_RM: ${get_kl54_rm()}
			ART_ABSTAND: ${get_art_abstand()}
			ART_VH: ${get_art_vh()}
			GBL_AUS: ${get_gbl_aus()}
			FZGVERSN: ${get_fzgversn()}
			LDC: ${get_ldc()}
		""".trimIndent()
	}


	private fun getParam(o: Int, l: Int) : Int = CanBusNative.getECUParameterC(CanCAddrs.EZS_240h, o, l)
}
