
package com.rndash.mbheadunit.nativeCan.canC

import com.rndash.mbheadunit.nativeCan.CanBusNative // AUTO GEN

/**
 *   Generated by db_converter.py
 *   Object for FBS_112h (ID 0x0112)
**/

object FBS_112h {

    	/** Gets FBS message to GS (8 bytes) **/
	fun get_fbs_gs() : Int = CanBusNative.getECUParameterC(CanCAddrs.FBS_112h, 0, 64)
	
	
}
