
@file:Suppress("unused", "FunctionName", "ClassName")
package com.rndash.mbheadunit.nativeCan.canC
import com.rndash.mbheadunit.CanFrame // AUTO GEN
import com.rndash.mbheadunit.nativeCan.CanBusNative // AUTO GEN

/**
 *   Generated by db_converter.py
 *   Object for GS_102h (ID 0x0102)
**/

object GS_102h {

    /** 
     *  Returns the most recent Can Frame representing the state
     *  of GS_102h
    **/
    fun get_frame() : CanFrame? = CanBusNative.getCFrame(CanCAddrs.GS_102h)

	/** Gets FBS message to EZS (8 bytes) **/
	fun get_gs_fbs() : Int = CanBusNative.getECUParameterC(CanCAddrs.GS_102h, 0, 64)
	
	/** Sets FBS message to EZS (8 bytes) **/
	fun set_gs_fbs(f: CanFrame, p: Int) {
		checkFrame(f)
		CanBusNative.setFrameParameter(f, 0, 64, p)
	}
	
	/**
     * Auto generated function
     * Throws exception if user tries to set a value in a frame
     * Not designated from the correct ECU
    **/
    private fun checkFrame(f: CanFrame) {
        if (f.canID != CanCAddrs.GS_102h.addr) {
            throw IllegalArgumentException("CAN ID does not match object!")
        }
    }

	override fun toString() = """
		|Frame GS_102h (0x0102):
		|	FBS message to EZS (8 bytes): ${get_gs_fbs()}
	""".trimMargin("|")
}
