
package com.rndash.mbheadunit.nativeCan.canC

import com.rndash.mbheadunit.nativeCan.CanBusNative // AUTO GEN

/**
 *   Generated by db_converter.py
 *   Object for GS_APPL1 (ID 0x051C)
**/

object GS_APPL1 {

    	/** Gets application **/
	fun get_appl1() : Int = CanBusNative.getECUParameterC(CanCAddrs.GS_APPL1, 0, 64)
	
	
}
