
@file:Suppress("unused", "FunctionName", "ClassName")
package com.rndash.mbheadunit.nativeCan.canC
import com.rndash.mbheadunit.CanFrame // AUTO GEN
import com.rndash.mbheadunit.nativeCan.CanBusNative // AUTO GEN

/**
 *   Generated by db_converter.py
 *   Object for GS_APPL1 (ID 0x051C)
**/

object GS_APPL1 {

    /** 
     *  Returns the most recent Can Frame representing the state
     *  of GS_APPL1
    **/
    fun get_frame() : CanFrame? = CanBusNative.getCFrame(CanCAddrs.GS_APPL1)

	/** Gets application **/
	fun get_appl1() : Int = CanBusNative.getECUParameterC(CanCAddrs.GS_APPL1, 0, 64)
	
	/** Sets application **/
	fun set_appl1(f: CanFrame, p: Int) : CanFrame? {
		checkFrame(f)
		return CanBusNative.setFrameParameter(f, 0, 64, p)
	}
	
	/**
     * Auto generated function
     * Throws exception if user tries to set a value in a frame
     * Not designated from the correct ECU
    **/
    private fun checkFrame(f: CanFrame) {
        if (f.canID != CanCAddrs.GS_APPL1.addr) {
            throw IllegalArgumentException("CAN ID does not match object!")
        }
    }

	override fun toString() = """
		|application: ${get_appl1()}
	""".trimMargin("|")
}
