package com.rndash.mbheadunit.nativeCan.canC


import com.rndash.mbheadunit.nativeCan.CanCAddrs
import com.rndash.mbheadunit.nativeCan.CanBusNative



/**
 *    GENERATED BY parse_kt.py
 *    Decoder class for ECU Frame GS_HSA (ID: 0x050A)
**/
object GS_HSA {

	/** Handsteuerung am Prüfstand **/
	fun get_hsa() : Int = getParam(0, 64)

	override fun toString(): String {
		return """
			HSA: ${get_hsa()}
		""".trimIndent()
	}


	private fun getParam(o: Int, l: Int) : Int = CanBusNative.getECUParameterC(CanCAddrs.GS_HSA, o, l)
}
