package com.rndash.mbheadunit.nativeCan.canC


import com.rndash.mbheadunit.nativeCan.CanCAddrs
import com.rndash.mbheadunit.nativeCan.CanBusNative



/**
 *    GENERATED BY parse_kt.py
 *    Decoder class for ECU Frame GS_HSD (ID: 0x050D)
**/
object GS_HSD {

	/** Handsteuerung am Prüfstand **/
	fun get_hsd() : Int = getParam(0, 64)

	override fun toString(): String {
		return """
			HSD: ${get_hsd()}
		""".trimIndent()
	}


	private fun getParam(o: Int, l: Int) : Int = CanBusNative.getECUParameterC(CanCAddrs.GS_HSD, o, l)
}
