
package com.rndash.mbheadunit.nativeCan.canC

import com.rndash.mbheadunit.nativeCan.CanBusNative // AUTO GEN

/**
 *   Generated by db_converter.py
 *   Object for GS_HSD (ID 0x050D)
**/

object GS_HSD {

    	/** Gets manual control on the test bench **/
	fun get_hsd() : Int = CanBusNative.getECUParameterC(CanCAddrs.GS_HSD, 0, 64)
	
	
}
