
package com.rndash.mbheadunit.nativeCan.canC

import com.rndash.mbheadunit.nativeCan.CanBusNative // AUTO GEN

/**
 *   Generated by db_converter.py
 *   Object for GS_HS1 (ID 0x0501)
**/

object GS_HS1 {

    	/** Gets manual control on the test bench **/
	fun get_hs1() : Int = CanBusNative.getECUParameterC(CanCAddrs.GS_HS1, 0, 64)
	
	
}
