package com.rndash.mbheadunit.nativeCan.canC


import com.rndash.mbheadunit.nativeCan.CanCAddrs
import com.rndash.mbheadunit.nativeCan.CanBusNative



/**
 *    GENERATED BY parse_kt.py
 *    Decoder class for ECU Frame GS_HS1 (ID: 0x0501)
**/
object GS_HS1 {

	/** Handsteuerung am Prüfstand **/
	fun get_hs1() : Int = getParam(0, 64)

	override fun toString(): String {
		return """
			HS1: ${get_hs1()}
		""".trimIndent()
	}


	private fun getParam(o: Int, l: Int) : Int = CanBusNative.getECUParameterC(CanCAddrs.GS_HS1, o, l)
}
