
@file:Suppress("unused", "FunctionName")
package com.rndash.mbheadunit.nativeCan.canC
import com.rndash.mbheadunit.CanFrame // AUTO GEN
import com.rndash.mbheadunit.nativeCan.CanBusNative // AUTO GEN

/**
 *   Generated by db_converter.py
 *   Object for GS_HSC (ID 0x050C)
**/

object GS_HSC {

    	/** Gets manual control on the test bench **/
	fun get_hsc() : Int = CanBusNative.getECUParameterC(CanCAddrs.GS_HSC, 0, 64)
	
	/** Sets manual control on the test bench **/
	fun set_hsc(f: CanFrame, p: Int) = CanBusNative.setFrameParameter(f, 0, 64, p)
	
	
}
