
package com.rndash.mbheadunit.nativeCan.canC

import com.rndash.mbheadunit.nativeCan.CanBusNative // AUTO GEN

/**
 *   Generated by db_converter.py
 *   Object for GS_HS2 (ID 0x0502)
**/

object GS_HS2 {

    	/** Gets manual control on the test bench **/
	fun get_hs2() : Int = CanBusNative.getECUParameterC(CanCAddrs.GS_HS2, 0, 64)
	
	
}
