
package com.rndash.mbheadunit.nativeCan.canC

import com.rndash.mbheadunit.nativeCan.CanBusNative // AUTO GEN

/**
 *   Generated by db_converter.py
 *   Object for GS_HS5 (ID 0x0505)
**/

object GS_HS5 {

    	/** UNKNOWN DESCRIPTION **/
	fun get_hs5() : Int = CanBusNative.getECUParameterC(CanCAddrs.GS_HS5, 0, 64)
	
	
}
