
package com.rndash.mbheadunit.nativeCan.canC

import com.rndash.mbheadunit.nativeCan.CanBusNative // AUTO GEN

/**
 *   Generated by db_converter.py
 *   Object for GS_HS3 (ID 0x0503)
**/

object GS_HS3 {

    	/** Gets manual control on the test bench **/
	fun get_hs3() : Int = CanBusNative.getECUParameterC(CanCAddrs.GS_HS3, 0, 64)
	
	
}
