
@file:Suppress("unused", "FunctionName")
package com.rndash.mbheadunit.nativeCan.canC
import com.rndash.mbheadunit.CanFrame // AUTO GEN
import com.rndash.mbheadunit.nativeCan.CanBusNative // AUTO GEN

/**
 *   Generated by db_converter.py
 *   Object for GS_HSD (ID 0x050D)
**/

object GS_HSD {

    	/** Gets manual control on the test bench **/
	fun get_hsd() : Int = CanBusNative.getECUParameterC(CanCAddrs.GS_HSD, 0, 64)
	
	/** Sets manual control on the test bench **/
	fun set_hsd(f: CanFrame, p: Int) = CanBusNative.setFrameParameter(f, 0, 64, p)
	
	
}
