package com.rndash.mbheadunit.nativeCan.canC


import com.rndash.mbheadunit.nativeCan.CanCAddrs
import com.rndash.mbheadunit.nativeCan.CanBusNative



/**
 *    GENERATED BY parse_kt.py
 *    Decoder class for ECU Frame KLA_410h (ID: 0x0410)
**/
object KLA_410h {

	/** Heater switch allows **/
	fun get_zh_ein_ok() : Boolean = getParam(0, 1) != 0

	/** Idle speed increase for the cooling capacity increase **/
	fun get_ll_dza() : Boolean = getParam(1, 1) != 0

	/** Air compressor switched **/
	fun get_komp_ein() : Boolean = getParam(7, 1) != 0

	/** Refrigerant pressure **/
	fun get_p_kaelte8() : Int = getParam(8, 8)

	/** Torque absorption chiller **/
	fun get_m_komp() : Int = getParam(16, 8)

	/** Motor fan set speed **/
	fun get_nlfts() : Int = getParam(24, 8)

	/** Outside air temperature for heat management **/
	fun get_t_aussen_wm() : Int = getParam(40, 8)

	override fun toString(): String {
		return """
			ZH_EIN_OK: ${get_zh_ein_ok()}
			LL_DZA: ${get_ll_dza()}
			KOMP_EIN: ${get_komp_ein()}
			P_KAELTE8: ${get_p_kaelte8()}
			M_KOMP: ${get_m_komp()}
			NLFTS: ${get_nlfts()}
			T_AUSSEN_WM: ${get_t_aussen_wm()}
		""".trimIndent()
	}


	private fun getParam(o: Int, l: Int) : Int = CanBusNative.getECUParameterC(CanCAddrs.KLA_410h, o, l)
}
