
package com.rndash.mbheadunit.nativeCan.canC

import com.rndash.mbheadunit.nativeCan.CanBusNative // AUTO GEN

/**
 *   Generated by db_converter.py
 *   Object for KLA_410h (ID 0x0410)
**/

object KLA_410h {

    	/** Gets A / C compressor switched on **/
	fun get_komp_ein() : Boolean = CanBusNative.getECUParameterC(CanCAddrs.KLA_410h, 7, 1) != 0
	
	/** Gets Idle speed increase to increase the cooling capacity **/
	fun get_ll_dza() : Boolean = CanBusNative.getECUParameterC(CanCAddrs.KLA_410h, 1, 1) != 0
	
	/** Gets Switching on auxiliary heater allowed **/
	fun get_zh_ein_ok() : Boolean = CanBusNative.getECUParameterC(CanCAddrs.KLA_410h, 0, 1) != 0
	
	/** Gets refrigerant pressure **/
	fun get_p_kaelte8() : Int = CanBusNative.getECUParameterC(CanCAddrs.KLA_410h, 8, 8)
	
	/** Gets Torque absorption refrigeration compressor **/
	fun get_m_komp() : Int = CanBusNative.getECUParameterC(CanCAddrs.KLA_410h, 16, 8)
	
	/** Gets Motor fan setpoint speed **/
	fun get_nlfts() : Int = CanBusNative.getECUParameterC(CanCAddrs.KLA_410h, 24, 8)
	
	/** Gets outside air temperature for heat management **/
	fun get_t_aussen_wm() : Int = CanBusNative.getECUParameterC(CanCAddrs.KLA_410h, 40, 8)
	
	
}
