package com.rndash.mbheadunit.nativeCan.canC


import com.rndash.mbheadunit.nativeCan.CanCAddrs
import com.rndash.mbheadunit.nativeCan.CanBusNative



/**
 *    GENERATED BY parse_kt.py
 *    Decoder class for ECU Frame KOMBI_408h (ID: 0x0408)
**/
object KOMBI_408h {

	/** tank level **/
	fun get_tank_fs() : Int = getParam(0, 8)

	/** Driver's door **/
	fun get_tf_auf() : Boolean = getParam(8, 1) != 0

	/** Geschw.begrenzer- / cruise control display not possible **/
	fun get_v_dspl_aus() : Boolean = getParam(9, 1) != 0

	/** Tachoeichung **/
	fun get_tacho_sym() : Boolean = getParam(10, 1) != 0

	/** mph instead km / h (variable Geschwindigkeitsbegr.) **/
	fun get_v_mph() : Boolean = getParam(11, 1) != 0

	/** Air conditioning available **/
	fun get_kla_vh() : Boolean = getParam(12, 1) != 0

	/** Preglow pilot defective **/
	fun get_vgl_kl_def() : Boolean = getParam(13, 1) != 0

	/** Tank level minimum **/
	fun get_tfsm() : Boolean = getParam(14, 1) != 0

	/** Terminal 61 decoupled **/
	fun get_kl_61e() : Boolean = getParam(15, 1) != 0

	/** Outside air temperature raw value **/
	fun get_t_aussen() : Int = getParam(16, 8)

	/** Terminal 58 dimmed **/
	fun get_kl_58d() : Int = getParam(24, 8)

	/** Motorabstellzeit (is sent from terminal 15) **/
	fun get_maz() : Int = getParam(32, 8)

	/** mileage **/
	fun get_km16() : Int = getParam(40, 16)

	/** Winter tire speed Bit 3 **/
	fun get_wrc3() : Boolean = getParam(56, 1) != 0

	/** Geschw.begrenzer- / cruise control display active **/
	fun get_v_dspl_akt() : Boolean = getParam(57, 1) != 0

	/** Segment tachometer available **/
	fun get_sgt_vh() : Boolean = getParam(58, 1) != 0

	/** enable auxiliary heaters **/
	fun get_zh_freig() : Boolean = getParam(59, 1) != 0

	/** Roll test mode ESP switch **/
	fun get_rt_ein() : Boolean = getParam(60, 1) != 0

	/** Winter tire speed with 4 bits **/
	fun get_wrc() : Int = getParam(61, 3)

	override fun toString(): String {
		return """
			TANK_FS: ${get_tank_fs()}
			TF_AUF: ${get_tf_auf()}
			V_DSPL_AUS: ${get_v_dspl_aus()}
			TACHO_SYM: ${get_tacho_sym()}
			V_MPH: ${get_v_mph()}
			KLA_VH: ${get_kla_vh()}
			VGL_KL_DEF: ${get_vgl_kl_def()}
			TFSM: ${get_tfsm()}
			KL_61E: ${get_kl_61e()}
			T_AUSSEN: ${get_t_aussen()}
			KL_58D: ${get_kl_58d()}
			MAZ: ${get_maz()}
			KM16: ${get_km16()}
			WRC3: ${get_wrc3()}
			V_DSPL_AKT: ${get_v_dspl_akt()}
			SGT_VH: ${get_sgt_vh()}
			ZH_FREIG: ${get_zh_freig()}
			RT_EIN: ${get_rt_ein()}
			WRC: ${get_wrc()}
		""".trimIndent()
	}


	private fun getParam(o: Int, l: Int) : Int = CanBusNative.getECUParameterC(CanCAddrs.KOMBI_408h, o, l)
}
