
package com.rndash.mbheadunit.nativeCan.canC

import com.rndash.mbheadunit.nativeCan.CanBusNative // AUTO GEN

/**
 *   Generated by db_converter.py
 *   Object for KOMBI_408h (ID 0x0408)
**/

object KOMBI_408h {

    	/** Gets tank level **/
	fun get_tank_fs() : Int = CanBusNative.getECUParameterC(CanCAddrs.KOMBI_408h, 0, 8)
	
	/** Gets Terminal 61 decoupled **/
	fun get_kl_61e() : Boolean = CanBusNative.getECUParameterC(CanCAddrs.KOMBI_408h, 15, 1) != 0
	
	/** Gets minimum tank level **/
	fun get_tfsm() : Boolean = CanBusNative.getECUParameterC(CanCAddrs.KOMBI_408h, 14, 1) != 0
	
	/** Gets Pre-glow control lamp defective **/
	fun get_vgl_kl_def() : Boolean = CanBusNative.getECUParameterC(CanCAddrs.KOMBI_408h, 13, 1) != 0
	
	/** Gets air conditioning available **/
	fun get_kla_vh() : Boolean = CanBusNative.getECUParameterC(CanCAddrs.KOMBI_408h, 12, 1) != 0
	
	/** Gets mph instead of km / h (variable speed limit) **/
	fun get_v_mph() : Boolean = CanBusNative.getECUParameterC(CanCAddrs.KOMBI_408h, 11, 1) != 0
	
	/** Gets Tacho calibration **/
	fun get_tacho_sym() : Boolean = CanBusNative.getECUParameterC(CanCAddrs.KOMBI_408h, 10, 1) != 0
	
	/** Gets Speed ​​limiter / tempomat display not possible **/
	fun get_v_dspl_aus() : Boolean = CanBusNative.getECUParameterC(CanCAddrs.KOMBI_408h, 9, 1) != 0
	
	/** Gets driver's door open **/
	fun get_tf_auf() : Boolean = CanBusNative.getECUParameterC(CanCAddrs.KOMBI_408h, 8, 1) != 0
	
	/** Gets Raw outside air temperature **/
	fun get_t_aussen() : Int = CanBusNative.getECUParameterC(CanCAddrs.KOMBI_408h, 16, 8)
	
	/** Gets Terminal 58 dimmed **/
	fun get_kl_58d() : Int = CanBusNative.getECUParameterC(CanCAddrs.KOMBI_408h, 24, 8)
	
	/** Gets engine shutdown time (is sent from terminal 15) **/
	fun get_maz() : Int = CanBusNative.getECUParameterC(CanCAddrs.KOMBI_408h, 32, 8)
	
	/** Gets mileage **/
	fun get_km16() : Int = CanBusNative.getECUParameterC(CanCAddrs.KOMBI_408h, 40, 16)
	
	/** Gets maximum winter tire speed with 4 bits **/
	fun get_wrc() : WRC = when(CanBusNative.getECUParameterC(CanCAddrs.KOMBI_408h, 61, 3)) {
		 0 -> WRC.UBG
		 1 -> WRC.BG210
		 2 -> WRC.BG190
		 3 -> WRC.BG160
		 4 -> WRC.BG240
		 5 -> WRC.BG230
		 6 -> WRC.BG220
		 7 -> WRC.BG200
		 128 -> WRC.BG180
		 129 -> WRC.BG170
		 130 -> WRC.BG150
		 131 -> WRC.BG140
		 132 -> WRC.BG130
		 133 -> WRC.BG120
		 134 -> WRC.BG110
		 135 -> WRC.BG100
		 else -> throw Exception("Invalid raw value for WRC")
	}
	
	/** Gets Activate roller test mode ESP **/
	fun get_rt_ein() : Boolean = CanBusNative.getECUParameterC(CanCAddrs.KOMBI_408h, 60, 1) != 0
	
	/** Gets Enable auxiliary heater **/
	fun get_zh_freig() : Boolean = CanBusNative.getECUParameterC(CanCAddrs.KOMBI_408h, 59, 1) != 0
	
	/** Gets segment tachometer available **/
	fun get_sgt_vh() : Boolean = CanBusNative.getECUParameterC(CanCAddrs.KOMBI_408h, 58, 1) != 0
	
	/** Gets Speed ​​limiter / cruise control display active **/
	fun get_v_dspl_akt() : Boolean = CanBusNative.getECUParameterC(CanCAddrs.KOMBI_408h, 57, 1) != 0
	
	/** Gets Winter tire maximum speed bit 3 **/
	fun get_wrc3() : Boolean = CanBusNative.getECUParameterC(CanCAddrs.KOMBI_408h, 56, 1) != 0
	
	
}
