package com.rndash.mbheadunit.nativeCan.canC


import com.rndash.mbheadunit.nativeCan.CanCAddrs
import com.rndash.mbheadunit.nativeCan.CanBusNative



/**
 *    GENERATED BY parse_kt.py
 *    Decoder class for ECU Frame LRW_236h (ID: 0x0236)
**/
object LRW_236h {

	/** steering wheel angle **/
	fun get_lrw() : Int = getParam(2, 14)

	/** Steering wheel angle speed **/
	fun get_vlrw() : Int = getParam(18, 14)

	/** message count **/
	fun get_bz236h() : Int = getParam(32, 4)

	/** Identification steering wheel angle sensor **/
	fun get_lrws_id() : Int = getParam(36, 2)

	/** Status steering wheel angle sensor **/
	fun get_lrws_st() : Int = getParam(38, 2)

	/** CRC checksum byte 1-7 to SAE J1850 **/
	fun get_crc236h() : Int = getParam(56, 8)

	override fun toString(): String {
		return """
			LRW: ${get_lrw()}
			VLRW: ${get_vlrw()}
			BZ236h: ${get_bz236h()}
			LRWS_ID: ${get_lrws_id()}
			LRWS_ST: ${get_lrws_st()}
			CRC236h: ${get_crc236h()}
		""".trimIndent()
	}


	private fun getParam(o: Int, l: Int) : Int = CanBusNative.getECUParameterC(CanCAddrs.LRW_236h, o, l)
}
