
package com.rndash.mbheadunit.nativeCan.canC

import com.rndash.mbheadunit.nativeCan.CanBusNative // AUTO GEN

/**
 *   Generated by db_converter.py
 *   Object for LRW_236h (ID 0x0236)
**/

object LRW_236h {

    	/** Gets steering wheel angle **/
	fun get_lrw() : Int = CanBusNative.getECUParameterC(CanCAddrs.LRW_236h, 2, 14)
	
	/** Gets steering wheel angular speed **/
	fun get_vlrw() : Int = CanBusNative.getECUParameterC(CanCAddrs.LRW_236h, 18, 14)
	
	/** Gets Steering wheel angle sensor status **/
	fun get_lrws_st() : LRWS_ST = when(CanBusNative.getECUParameterC(CanCAddrs.LRW_236h, 38, 2)) {
		 0 -> LRWS_ST.OK
		 1 -> LRWS_ST.INI
		 2 -> LRWS_ST.ERR
		 3 -> LRWS_ST.ERR_INI
		 else -> throw Exception("Invalid raw value for LRWS_ST")
	}
	
	/** Gets Identification of the steering wheel angle sensor **/
	fun get_lrws_id() : LRWS_ID = when(CanBusNative.getECUParameterC(CanCAddrs.LRW_236h, 36, 2)) {
		 0 -> LRWS_ID.INIT_PSBL
		 1 -> LRWS_ID.INIT_SELF
		 2 -> LRWS_ID.INIT_MUST
		 3 -> LRWS_ID.SNV
		 else -> throw Exception("Invalid raw value for LRWS_ID")
	}
	
	/** Gets message counter **/
	fun get_bz236h() : Int = CanBusNative.getECUParameterC(CanCAddrs.LRW_236h, 32, 4)
	
	/** Gets CRC checksum byte 1 **/
	fun get_crc236h() : Int = CanBusNative.getECUParameterC(CanCAddrs.LRW_236h, 56, 8)
	
	
}
