
@file:Suppress("unused", "FunctionName")
package com.rndash.mbheadunit.nativeCan.canC
import com.rndash.mbheadunit.CanFrame // AUTO GEN
import com.rndash.mbheadunit.nativeCan.CanBusNative // AUTO GEN

/**
 *   Generated by db_converter.py
 *   Object for MS_101h (ID 0x0101)
**/

object MS_101h {

    	/** Gets FBS message to EZS (8 bytes) **/
	fun get_ms_fbs() : Int = CanBusNative.getECUParameterC(CanCAddrs.MS_101h, 0, 64)
	
	/** Sets FBS message to EZS (8 bytes) **/
	fun set_ms_fbs(f: CanFrame, p: Int) = CanBusNative.setFrameParameter(f, 0, 64, p)
	
	
}
