package com.rndash.mbheadunit.nativeCan.canC


import com.rndash.mbheadunit.nativeCan.CanCAddrs
import com.rndash.mbheadunit.nativeCan.CanBusNative



/**
 *    GENERATED BY parse_kt.py
 *    Decoder class for ECU Frame MS_101h (ID: 0x0101)
**/
object MS_101h {

	/** FBS-Botschaft an EZS (8 Byte) **/
	fun get_ms_fbs() : Int = getParam(0, 64)

	override fun toString(): String {
		return """
			MS_FBS: ${get_ms_fbs()}
		""".trimIndent()
	}


	private fun getParam(o: Int, l: Int) : Int = CanBusNative.getECUParameterC(CanCAddrs.MS_101h, o, l)
}
