package com.rndash.mbheadunit.nativeCan.canC


import com.rndash.mbheadunit.nativeCan.CanCAddrs
import com.rndash.mbheadunit.nativeCan.CanBusNative



/**
 *    GENERATED BY parse_kt.py
 *    Decoder class for ECU Frame MS_212h (ID: 0x0212)
**/
object MS_212h {

	/** Engine idling target speed **/
	fun get_nmots() : Int = getParam(0, 16)

	/** Series Cruise control is variant encodes **/
	fun get_tm_ms() : Boolean = getParam(17, 1) != 0

	/** Enable torque requirement ART **/
	fun get_m_art_e() : Boolean = getParam(18, 1) != 0

	/** Default moment driver **/
	fun get_m_fv() : Int = getParam(19, 13)

	/** Enable Quick torque adjustment **/
	fun get_sme_e() : Boolean = getParam(33, 1) != 0

	/** Enable torque request ESP **/
	fun get_m_esp_e() : Boolean = getParam(34, 1) != 0

	/** Spare default torque driver **/
	fun get_m_fev() : Int = getParam(35, 13)

	/** Transmission CALID / CVN enable **/
	fun get_calid_cvn_e() : Boolean = getParam(48, 1) != 0

	/** Acknowledgment torque request EGS **/
	fun get_m_egs_q() : Boolean = getParam(49, 1) != 0

	/** Enable torque request EGS **/
	fun get_m_egs_e() : Boolean = getParam(50, 1) != 0

	/** Default moment ESP **/
	fun get_m_espv() : Int = getParam(51, 13)

	override fun toString(): String {
		return """
			NMOTS: ${get_nmots()}
			TM_MS: ${get_tm_ms()}
			M_ART_E: ${get_m_art_e()}
			M_FV: ${get_m_fv()}
			SME_E: ${get_sme_e()}
			M_ESP_E: ${get_m_esp_e()}
			M_FEV: ${get_m_fev()}
			CALID_CVN_E: ${get_calid_cvn_e()}
			M_EGS_Q: ${get_m_egs_q()}
			M_EGS_E: ${get_m_egs_e()}
			M_ESPV: ${get_m_espv()}
		""".trimIndent()
	}


	private fun getParam(o: Int, l: Int) : Int = CanBusNative.getECUParameterC(CanCAddrs.MS_212h, o, l)
}
