package com.rndash.mbheadunit.nativeCan.canC


import com.rndash.mbheadunit.nativeCan.CanCAddrs
import com.rndash.mbheadunit.nativeCan.CanBusNative



/**
 *    GENERATED BY parse_kt.py
 *    Decoder class for ECU Frame MS_268h (ID: 0x0268)
**/
object MS_268h {

	/** Target speed, lower limit (fcvt) **/
	fun get_imin_ms() : Int = getParam(0, 8)

	/** Target speed, upper limit (fcvt) **/
	fun get_imax_ms() : Int = getParam(8, 8)

	/** terminal 61 **/
	fun get_kl_61_ein() : Boolean = getParam(16, 1) != 0

	/** Oil Info, Reserved M266 **/
	fun get_oel_info_169() : Boolean = getParam(17, 1) != 0

	/** Shut-off valve cooling circuit M266 ATL **/
	fun get_asv_kkl_169() : Boolean = getParam(18, 1) != 0

	/** status heating **/
	fun get_hzl_st() : Int = getParam(22, 2)

	/** Request force in free "D" (fcvt) **/
	fun get_kid_ms() : Boolean = getParam(24, 1) != 0

	/** Mode air control system **/
	fun get_lrs_mode() : Boolean = getParam(25, 1) != 0

	/** Generator capacity utilization (for LIN generators!) **/
	fun get_last_gen() : Int = getParam(26, 6)

	/** Max. Air Compressor moment **/
	fun get_m_komp_max() : Int = getParam(32, 8)

	/** Pedal value drivers (only 169) **/
	fun get_pw_f() : Int = getParam(40, 8)

	override fun toString(): String {
		return """
			IMIN_MS: ${get_imin_ms()}
			IMAX_MS: ${get_imax_ms()}
			KL_61_EIN: ${get_kl_61_ein()}
			OEL_INFO_169: ${get_oel_info_169()}
			ASV_KKL_169: ${get_asv_kkl_169()}
			HZL_ST: ${get_hzl_st()}
			KID_MS: ${get_kid_ms()}
			LRS_MODE: ${get_lrs_mode()}
			LAST_GEN: ${get_last_gen()}
			M_KOMP_MAX: ${get_m_komp_max()}
			PW_F: ${get_pw_f()}
		""".trimIndent()
	}


	private fun getParam(o: Int, l: Int) : Int = CanBusNative.getECUParameterC(CanCAddrs.MS_268h, o, l)
}
