
package com.rndash.mbheadunit.nativeCan.canC

import com.rndash.mbheadunit.nativeCan.CanBusNative // AUTO GEN

/**
 *   Generated by db_converter.py
 *   Object for MS_212h (ID 0x0212)
**/

object MS_212h {

    	/** Gets Target engine idling speed **/
	fun get_nmots() : Int = CanBusNative.getECUParameterC(CanCAddrs.MS_212h, 0, 16)
	
	/** Gets Enable torque request ART **/
	fun get_m_art_e() : Boolean = CanBusNative.getECUParameterC(CanCAddrs.MS_212h, 18, 1) != 0
	
	/** Gets Series cruise control is variant-coded **/
	fun get_tm_ms() : Boolean = CanBusNative.getECUParameterC(CanCAddrs.MS_212h, 17, 1) != 0
	
	/** Gets driver default torque **/
	fun get_m_fv() : Int = CanBusNative.getECUParameterC(CanCAddrs.MS_212h, 19, 13)
	
	/** Gets Enable torque request ESP **/
	fun get_m_esp_e() : Boolean = CanBusNative.getECUParameterC(CanCAddrs.MS_212h, 34, 1) != 0
	
	/** Gets Enable fast torque setting **/
	fun get_sme_e() : Boolean = CanBusNative.getECUParameterC(CanCAddrs.MS_212h, 33, 1) != 0
	
	/** Gets Substitute default torque driver **/
	fun get_m_fev() : Int = CanBusNative.getECUParameterC(CanCAddrs.MS_212h, 35, 13)
	
	/** Gets Enable torque request EGS **/
	fun get_m_egs_e() : Boolean = CanBusNative.getECUParameterC(CanCAddrs.MS_212h, 50, 1) != 0
	
	/** Gets Acknowledgment of torque request EGS **/
	fun get_m_egs_q() : Boolean = CanBusNative.getECUParameterC(CanCAddrs.MS_212h, 49, 1) != 0
	
	/** Gets Transfer CALID / CVN enable **/
	fun get_calid_cvn_e() : Boolean = CanBusNative.getECUParameterC(CanCAddrs.MS_212h, 48, 1) != 0
	
	/** Gets Preset torque ESP **/
	fun get_m_espv() : Int = CanBusNative.getECUParameterC(CanCAddrs.MS_212h, 51, 13)
	
	
}
