package com.rndash.mbheadunit.nativeCan.canC


import com.rndash.mbheadunit.nativeCan.CanCAddrs
import com.rndash.mbheadunit.nativeCan.CanBusNative



/**
 *    GENERATED BY parse_kt.py
 *    Decoder class for ECU Frame MS_312h (ID: 0x0312)
**/
object MS_312h {

	/** Engine torque statically **/
	fun get_m_sta() : Int = getParam(3, 13)

	/** Engine torque maximum incl. Dyn. turbocharger share **/
	fun get_m_max_atl() : Int = getParam(19, 13)

	/** Engine torque maximum **/
	fun get_m_max() : Int = getParam(35, 13)

	/** Motor torque minimum **/
	fun get_m_min() : Int = getParam(51, 13)

	override fun toString(): String {
		return """
			M_STA: ${get_m_sta()}
			M_MAX_ATL: ${get_m_max_atl()}
			M_MAX: ${get_m_max()}
			M_MIN: ${get_m_min()}
		""".trimIndent()
	}


	private fun getParam(o: Int, l: Int) : Int = CanBusNative.getECUParameterC(CanCAddrs.MS_312h, o, l)
}
