
package com.rndash.mbheadunit.nativeCan.canC

import com.rndash.mbheadunit.nativeCan.CanBusNative // AUTO GEN

/**
 *   Generated by db_converter.py
 *   Object for MS_APPL7 (ID 0x0618)
**/

object MS_APPL7 {

    	/** Gets application **/
	fun get_appl7() : Int = CanBusNative.getECUParameterC(CanCAddrs.MS_APPL7, 0, 64)
	
	
}
