
package com.rndash.mbheadunit.nativeCan.canC

import com.rndash.mbheadunit.nativeCan.CanBusNative // AUTO GEN

/**
 *   Generated by db_converter.py
 *   Object for MS_APPL5 (ID 0x06A8)
**/

object MS_APPL5 {

    	/** Gets application **/
	fun get_appl5() : Int = CanBusNative.getECUParameterC(CanCAddrs.MS_APPL5, 0, 64)
	
	
}
