package com.rndash.mbheadunit.nativeCan.canC


import com.rndash.mbheadunit.nativeCan.CanCAddrs
import com.rndash.mbheadunit.nativeCan.CanBusNative



/**
 *    GENERATED BY parse_kt.py
 *    Decoder class for ECU Frame PSM_3B4h (ID: 0x03B4)
**/
object PSM_3B4h {

	/** Working speed control **/
	fun get_psm_adr_par() : Boolean = getParam(0, 1) != 0

	/** Working speed control **/
	fun get_psm_adr_tgl() : Boolean = getParam(1, 1) != 0

	/** Working speed control active **/
	fun get_psm_adr_akt() : Boolean = getParam(2, 1) != 0

	/** Target engine speed ADR **/
	fun get_psm_n_soll() : Int = getParam(8, 16)

	/** Torque limit **/
	fun get_psm_mom_par() : Boolean = getParam(24, 1) != 0

	/** Torque limit **/
	fun get_psm_mom_tgl() : Boolean = getParam(25, 1) != 0

	/** Torque limit active **/
	fun get_psm_mom_akt() : Boolean = getParam(26, 1) != 0

	/** Maximum engine torque **/
	fun get_psm_mom_soll() : Int = getParam(27, 13)

	/** Speed ​​limit **/
	fun get_psm_dz_par() : Boolean = getParam(40, 1) != 0

	/** Speed ​​limit **/
	fun get_psm_dz_tgl() : Boolean = getParam(41, 1) != 0

	/** Speed ​​limit active **/
	fun get_psm_dz_akt() : Boolean = getParam(42, 1) != 0

	/** maximum speed **/
	fun get_psm_dz_max() : Int = getParam(48, 16)

	override fun toString(): String {
		return """
			PSM_ADR_PAR: ${get_psm_adr_par()}
			PSM_ADR_TGL: ${get_psm_adr_tgl()}
			PSM_ADR_AKT: ${get_psm_adr_akt()}
			PSM_N_SOLL: ${get_psm_n_soll()}
			PSM_MOM_PAR: ${get_psm_mom_par()}
			PSM_MOM_TGL: ${get_psm_mom_tgl()}
			PSM_MOM_AKT: ${get_psm_mom_akt()}
			PSM_MOM_SOLL: ${get_psm_mom_soll()}
			PSM_DZ_PAR: ${get_psm_dz_par()}
			PSM_DZ_TGL: ${get_psm_dz_tgl()}
			PSM_DZ_AKT: ${get_psm_dz_akt()}
			PSM_DZ_MAX: ${get_psm_dz_max()}
		""".trimIndent()
	}


	private fun getParam(o: Int, l: Int) : Int = CanBusNative.getECUParameterC(CanCAddrs.PSM_3B4h, o, l)
}
