package com.rndash.mbheadunit.nativeCan.canC


import com.rndash.mbheadunit.nativeCan.CanCAddrs
import com.rndash.mbheadunit.nativeCan.CanBusNative



/**
 *    GENERATED BY parse_kt.py
 *    Decoder class for ECU Frame PSM_3B8h (ID: 0x03B8)
**/
object PSM_3B8h {

	/** Speed ​​limit **/
	fun get_psm_v_par() : Boolean = getParam(0, 1) != 0

	/** Speed ​​limit **/
	fun get_psm_v_tgl() : Boolean = getParam(1, 1) != 0

	/** Speed ​​limit active **/
	fun get_psm_v_akt() : Boolean = getParam(2, 1) != 0

	/** speed limit **/
	fun get_psm_v_soll() : Int = getParam(8, 8)

	/** Speed ​​limit **/
	fun get_psm_dz_par() : Boolean = getParam(16, 1) != 0

	/** Speed ​​limit **/
	fun get_psm_dz_tgl() : Boolean = getParam(17, 1) != 0

	/** Remote engine start active **/
	fun get_psm_fern_start() : Boolean = getParam(18, 1) != 0

	/** Remote engine stop active **/
	fun get_psm_fern_stop() : Boolean = getParam(19, 1) != 0

	/** Lock accelerator pedal module **/
	fun get_psm_fpm_sp() : Boolean = getParam(20, 1) != 0

	override fun toString(): String {
		return """
			PSM_V_PAR: ${get_psm_v_par()}
			PSM_V_TGL: ${get_psm_v_tgl()}
			PSM_V_AKT: ${get_psm_v_akt()}
			PSM_V_SOLL: ${get_psm_v_soll()}
			PSM_DZ_PAR: ${get_psm_dz_par()}
			PSM_DZ_TGL: ${get_psm_dz_tgl()}
			PSM_FERN_START: ${get_psm_fern_start()}
			PSM_FERN_STOP: ${get_psm_fern_stop()}
			PSM_FPM_SP: ${get_psm_fpm_sp()}
		""".trimIndent()
	}


	private fun getParam(o: Int, l: Int) : Int = CanBusNative.getECUParameterC(CanCAddrs.PSM_3B8h, o, l)
}
