
package com.rndash.mbheadunit.nativeCan.canC

import com.rndash.mbheadunit.nativeCan.CanBusNative // AUTO GEN

/**
 *   Generated by db_converter.py
 *   Object for PSM_3B8h (ID 0x03B8)
**/

object PSM_3B8h {

    	/** Gets speed limit active **/
	fun get_psm_v_akt() : Boolean = CanBusNative.getECUParameterC(CanCAddrs.PSM_3B8h, 2, 1) != 0
	
	/** Gets speed limit **/
	fun get_psm_v_tgl() : Boolean = CanBusNative.getECUParameterC(CanCAddrs.PSM_3B8h, 1, 1) != 0
	
	/** Gets speed limit **/
	fun get_psm_v_par() : Boolean = CanBusNative.getECUParameterC(CanCAddrs.PSM_3B8h, 0, 1) != 0
	
	/** Gets speed limit **/
	fun get_psm_v_soll() : Int = CanBusNative.getECUParameterC(CanCAddrs.PSM_3B8h, 8, 8)
	
	/** Gets Disable accelerator pedal module **/
	fun get_psm_fpm_sp() : Boolean = CanBusNative.getECUParameterC(CanCAddrs.PSM_3B8h, 20, 1) != 0
	
	/** Gets Motor remote stop active **/
	fun get_psm_fern_stop() : Boolean = CanBusNative.getECUParameterC(CanCAddrs.PSM_3B8h, 19, 1) != 0
	
	/** Gets Motor remote start active **/
	fun get_psm_fern_start() : Boolean = CanBusNative.getECUParameterC(CanCAddrs.PSM_3B8h, 18, 1) != 0
	
	/** Gets speed limitation **/
	fun get_psm_dz_tgl() : Boolean = CanBusNative.getECUParameterC(CanCAddrs.PSM_3B8h, 17, 1) != 0
	
	/** Gets speed limitation **/
	fun get_psm_dz_par() : Boolean = CanBusNative.getECUParameterC(CanCAddrs.PSM_3B8h, 16, 1) != 0
	
	
}
