
@file:Suppress("unused", "FunctionName")
package com.rndash.mbheadunit.nativeCan.canC
import com.rndash.mbheadunit.CanFrame // AUTO GEN
import com.rndash.mbheadunit.nativeCan.CanBusNative // AUTO GEN

/**
 *   Generated by db_converter.py
 *   Object for SBW_232h (ID 0x0232)
**/

object SBW_232h {

    	/** Gets Steering wheel buttons "+", "-" pressed **/
	fun get_lrt_pm3() : LRT_PM3 = when(CanBusNative.getECUParameterC(CanCAddrs.SBW_232h, 5, 3)) {
		 0 -> LRT_PM3.NBET
		 1 -> LRT_PM3.PLUS
		 2 -> LRT_PM3.MINUS
		 3 -> LRT_PM3.PLUS_MINUS
		 4 -> LRT_PM3.NOT_DEFINED
		 5 -> LRT_PM3.NOT_DEFINED_5
		 6 -> LRT_PM3.NOT_DEFINED_6
		 7 -> LRT_PM3.SNV
		 else -> throw Exception("Invalid raw value for LRT_PM3")
	}
	
	/** Sets Steering wheel buttons "+", "-" pressed **/
	fun set_lrt_pm3(f: CanFrame, p: LRT_PM3) = CanBusNative.setFrameParameter(f, 5, 3, p.raw)
	
	/** Gets sender identification **/
	fun get_sid_sbw() : SID_SBW = when(CanBusNative.getECUParameterC(CanCAddrs.SBW_232h, 0, 2)) {
		 0 -> SID_SBW.EWM
		 1 -> SID_SBW.MRM
		 2 -> SID_SBW.NOT_DEFINED
		 3 -> SID_SBW.NOT_DEFINED_3
		 else -> throw Exception("Invalid raw value for SID_SBW")
	}
	
	/** Sets sender identification **/
	fun set_sid_sbw(f: CanFrame, p: SID_SBW) = CanBusNative.setFrameParameter(f, 0, 2, p.raw)
	
	/** Gets Shift-by-wire control element Status RND **/
	fun get_sbwb_st_rnd() : SBWB_ST_RND = when(CanBusNative.getECUParameterC(CanCAddrs.SBW_232h, 12, 4)) {
		 0 -> SBWB_ST_RND.IDLE
		 1 -> SBWB_ST_RND.R
		 2 -> SBWB_ST_RND.N_OBEN
		 4 -> SBWB_ST_RND.N_UNTEN
		 6 -> SBWB_ST_RND.INIT
		 8 -> SBWB_ST_RND.D
		 15 -> SBWB_ST_RND.SNV
		 else -> throw Exception("Invalid raw value for SBWB_ST_RND")
	}
	
	/** Sets Shift-by-wire control element Status RND **/
	fun set_sbwb_st_rnd(f: CanFrame, p: SBWB_ST_RND) = CanBusNative.setFrameParameter(f, 12, 4, p.raw)
	
	/** Gets Shift-by-wire control element P button **/
	fun get_sbwb_st_p() : SBWB_ST_P = when(CanBusNative.getECUParameterC(CanCAddrs.SBW_232h, 10, 2)) {
		 0 -> SBWB_ST_P.IDLE
		 1 -> SBWB_ST_P.P
		 2 -> SBWB_ST_P.INIT
		 3 -> SBWB_ST_P.SNV
		 else -> throw Exception("Invalid raw value for SBWB_ST_P")
	}
	
	/** Sets Shift-by-wire control element P button **/
	fun set_sbwb_st_p(f: CanFrame, p: SBWB_ST_P) = CanBusNative.setFrameParameter(f, 10, 2, p.raw)
	
	/** Gets Shift-by-wire control element identification **/
	fun get_sbwb_id() : SBWB_ID = when(CanBusNative.getECUParameterC(CanCAddrs.SBW_232h, 8, 2)) {
		 0 -> SBWB_ID.GWHST_LR
		 2 -> SBWB_ID.RES_ALT_FEHLER
		 3 -> SBWB_ID.SBWB_ST_P_RND
		 else -> throw Exception("Invalid raw value for SBWB_ID")
	}
	
	/** Sets Shift-by-wire control element identification **/
	fun set_sbwb_id(f: CanFrame, p: SBWB_ID) = CanBusNative.setFrameParameter(f, 8, 2, p.raw)
	
	/** Gets message counter **/
	fun get_bz232h() : Int = CanBusNative.getECUParameterC(CanCAddrs.SBW_232h, 16, 4)
	
	/** Sets message counter **/
	fun set_bz232h(f: CanFrame, p: Int) = CanBusNative.setFrameParameter(f, 16, 4, p)
	
	
}
