
package com.rndash.mbheadunit.nativeCan.canC

import com.rndash.mbheadunit.nativeCan.CanBusNative // AUTO GEN

/**
 *   Generated by db_converter.py
 *   Object for ZGW_248h (ID 0x0248)
**/

object ZGW_248h {

    	/** Gets switch on low beam **/
	fun get_abl_ein() : Boolean = CanBusNative.getECUParameterC(CanCAddrs.ZGW_248h, 3, 1) != 0
	
	/** Gets Start Xenon4 diagnostic procedure on the driver's side **/
	fun get_diag_x4_f() : Boolean = CanBusNative.getECUParameterC(CanCAddrs.ZGW_248h, 1, 1) != 0
	
	/** Gets Start Xenon4 diagnostic procedure on the passenger side **/
	fun get_diag_x4_b() : Boolean = CanBusNative.getECUParameterC(CanCAddrs.ZGW_248h, 0, 1) != 0
	
	/** Gets Trailer operation detected **/
	fun get_anh_erk2() : ANH_ERK2 = when(CanBusNative.getECUParameterC(CanCAddrs.ZGW_248h, 14, 2)) {
		 0 -> ANH_ERK2.NONE
		 1 -> ANH_ERK2.OK
		 2 -> ANH_ERK2.NOT_DEFINED
		 3 -> ANH_ERK2.SNV
		 else -> throw Exception("Invalid raw value for ANH_ERK2")
	}
	
	/** Gets Auxiliary water pump is running **/
	fun get_zwp_lft() : Boolean = CanBusNative.getECUParameterC(CanCAddrs.ZGW_248h, 13, 1) != 0
	
	/** Gets AFL request: switch on low beam **/
	fun get_afl_abl_ein() : Boolean = CanBusNative.getECUParameterC(CanCAddrs.ZGW_248h, 12, 1) != 0
	
	
}
