package com.rndash.mbheadunit.nativeCan.canC


import com.rndash.mbheadunit.nativeCan.CanCAddrs
import com.rndash.mbheadunit.nativeCan.CanBusNative



/**
 *    GENERATED BY parse_kt.py
 *    Decoder class for ECU Frame ZGW_248h (ID: 0x0248)
**/
object ZGW_248h {

	/** Start Xenon4 diagnostic procedure passenger side **/
	fun get_diag_x4_b() : Boolean = getParam(0, 1) != 0

	/** Start Xenon4 diagnostic procedure driver's side **/
	fun get_diag_x4_f() : Boolean = getParam(1, 1) != 0

	/** switch on low beam **/
	fun get_abl_ein() : Boolean = getParam(3, 1) != 0

	/** AFL request: Switch low beam **/
	fun get_afl_abl_ein() : Boolean = getParam(12, 1) != 0

	/** Auxiliary water pump runs **/
	fun get_zwp_lft() : Boolean = getParam(13, 1) != 0

	/** Towing recognized **/
	fun get_anh_erk2() : Int = getParam(14, 2)

	override fun toString(): String {
		return """
			DIAG_X4_B: ${get_diag_x4_b()}
			DIAG_X4_F: ${get_diag_x4_f()}
			ABL_EIN: ${get_abl_ein()}
			AFL_ABL_EIN: ${get_afl_abl_ein()}
			ZWP_LFT: ${get_zwp_lft()}
			ANH_ERK2: ${get_anh_erk2()}
		""".trimIndent()
	}


	private fun getParam(o: Int, l: Int) : Int = CanBusNative.getECUParameterC(CanCAddrs.ZGW_248h, o, l)
}
