
package com.rndash.mbheadunit.nativeCan.canC

import com.rndash.mbheadunit.nativeCan.CanBusNative // AUTO GEN

/**
 *   Generated by db_converter.py
 *   Object for ZGW_24Ch (ID 0x024C)
**/

object ZGW_24Ch {

    	/** Gets low beam defective driver / left (depending on BR) **/
	fun get_abl_def_f_l() : Boolean = CanBusNative.getECUParameterC(CanCAddrs.ZGW_24Ch, 39, 1) != 0
	
	/** Gets dipped beam defective passenger / right (depending on BR) **/
	fun get_abl_def_bf_r() : Boolean = CanBusNative.getECUParameterC(CanCAddrs.ZGW_24Ch, 38, 1) != 0
	
	
}
