package com.rndash.mbheadunit.nativeCan.canB


import com.rndash.mbheadunit.nativeCan.CanBAddrs
import com.rndash.mbheadunit.nativeCan.CanBusNative



/**
 *    GENERATED BY parse_kt.py
 *    Decoder class for ECU Frame AAG_A1 (ID: 0x0130)
**/
object AAG_A1 {

	/** Towing recognized **/
	fun get_anh_erk() : Boolean = getParam(0, 1) != 0

	/** not locked trailer coupling **/
	fun get_ahk_nok() : Boolean = getParam(1, 1) != 0

	/** Trailer Terminal 54 errors **/
	fun get_anhkl_54_def() : Boolean = getParam(2, 1) != 0

	/** EDW trailer monitoring alarm triggered **/
	fun get_edw_anh_alm() : Boolean = getParam(3, 1) != 0

	/** Trailer brake light broken **/
	fun get_anhbl_def() : Boolean = getParam(7, 1) != 0

	/** Trailer left tail light broken **/
	fun get_anhsl_def_l() : Boolean = getParam(8, 1) != 0

	/** Trailer left turn signal defective **/
	fun get_anhbli_def_l() : Boolean = getParam(9, 1) != 0

	/** Trailer tail lamp right defective **/
	fun get_anhsl_def_r() : Boolean = getParam(12, 1) != 0

	/** Trailer right turn signal defective **/
	fun get_anhbli_def_r() : Boolean = getParam(13, 1) != 0

	override fun toString(): String {
		return """
			ANH_ERK: ${get_anh_erk()}
			AHK_NOK: ${get_ahk_nok()}
			ANHKL_54_DEF: ${get_anhkl_54_def()}
			EDW_ANH_ALM: ${get_edw_anh_alm()}
			ANHBL_DEF: ${get_anhbl_def()}
			ANHSL_DEF_L: ${get_anhsl_def_l()}
			ANHBLI_DEF_L: ${get_anhbli_def_l()}
			ANHSL_DEF_R: ${get_anhsl_def_r()}
			ANHBLI_DEF_R: ${get_anhbli_def_r()}
		""".trimIndent()
	}


	private fun getParam(o: Int, l: Int) : Int = CanBusNative.getECUParameterB(CanBAddrs.AAG_A1, o, l)
}
