
package com.rndash.mbheadunit.nativeCan.canB

import com.rndash.mbheadunit.nativeCan.CanBusNative // AUTO GEN

/**
 *   Generated by db_converter.py
 *   Object for AGW_A3 (ID 0x0138)
**/

object AGW_A3 {

    	/** Gets Numeric keypad head unit **/
	fun get_ziffer_hu() : ZIFFER_HU = when(CanBusNative.getECUParameterB(CanBAddrs.AGW_A3, 4, 4)) {
		 0 -> ZIFFER_HU.N_BET
		 1 -> ZIFFER_HU.T1_key
		 2 -> ZIFFER_HU.T2
		 3 -> ZIFFER_HU.T3
		 4 -> ZIFFER_HU.T4
		 5 -> ZIFFER_HU.T5
		 6 -> ZIFFER_HU.T6
		 7 -> ZIFFER_HU.T7
		 8 -> ZIFFER_HU.T8
		 9 -> ZIFFER_HU.T9_key
		 10 -> ZIFFER_HU.T10_button
		 else -> throw Exception("Invalid raw value for ZIFFER_HU")
	}
	
	/** Gets Diamond key pressed **/
	fun get_raute_hu() : Boolean = CanBusNative.getECUParameterB(CanBAddrs.AGW_A3, 3, 1) != 0
	
	/** Gets star key pressed **/
	fun get_stern_hu() : Boolean = CanBusNative.getECUParameterB(CanBAddrs.AGW_A3, 2, 1) != 0
	
	/** Gets Rejection of numeric entry HU **/
	fun get_cancel_hu() : Boolean = CanBusNative.getECUParameterB(CanBAddrs.AGW_A3, 1, 1) != 0
	
	/** Gets Active application **/
	fun get_akt_sys() : AKT_SYS = when(CanBusNative.getECUParameterB(CanBAddrs.AGW_A3, 13, 3)) {
		 0 -> AKT_SYS.IDLE
		 1 -> AKT_SYS.radio_data_transmission
		 else -> throw Exception("Invalid raw value for AKT_SYS")
	}
	
	/** Gets function keys **/
	fun get_function_keys() : FUNCTION_KEYS = when(CanBusNative.getECUParameterB(CanBAddrs.AGW_A3, 10, 3)) {
		 0 -> FUNCTION_KEYS.N_BET
		 1 -> FUNCTION_KEYS.F1
		 2 -> FUNCTION_KEYS.F2
		 3 -> FUNCTION_KEYS.F3
		 4 -> FUNCTION_KEYS.F4
		 5 -> FUNCTION_KEYS.F5
		 6 -> FUNCTION_KEYS.F6
		 7 -> FUNCTION_KEYS.F7
		 else -> throw Exception("Invalid raw value for FUNCTION_KEYS")
	}
	
	
}
