
package com.rndash.mbheadunit.nativeCan.canB

import com.rndash.mbheadunit.nativeCan.CanBusNative // AUTO GEN

/**
 *   Generated by db_converter.py
 *   Object for DBE_A4 (ID 0x0174)
**/

object DBE_A4 {

    	/** Gets Sliding / tilting roof closed when it rains **/
	fun get_shd_zu_rs() : Boolean = CanBusNative.getECUParameterB(CanBAddrs.DBE_A4, 0, 1) != 0
	
	
}
