package com.rndash.mbheadunit.nativeCan.canB


import com.rndash.mbheadunit.nativeCan.CanBAddrs
import com.rndash.mbheadunit.nativeCan.CanBusNative



/**
 *    GENERATED BY parse_kt.py
 *    Decoder class for ECU Frame EZS_A3 (ID: 0x01B8)
**/
object EZS_A3 {

	/** (km) Kilometerstand (bis ÄJ 2002/1) **/
	fun get_km_ezs_alt() : Int = getParam(0, 24)

	override fun toString(): String {
		return """
			KM_EZS_ALT: ${get_km_ezs_alt()}
		""".trimIndent()
	}


	private fun getParam(o: Int, l: Int) : Int = CanBusNative.getECUParameterB(CanBAddrs.EZS_A3, o, l)
}
