
package com.rndash.mbheadunit.nativeCan.canB

import com.rndash.mbheadunit.nativeCan.CanBusNative // AUTO GEN

/**
 *   Generated by db_converter.py
 *   Object for EZS_A4 (ID 0x0058)
**/

object EZS_A4 {

    	/** Gets Identification key for pre-filtering **/
	fun get_schlue_id() : Int = CanBusNative.getECUParameterB(CanBAddrs.EZS_A4, 0, 32)
	
	/** Gets Mileage UNIT: km **/
	fun get_km_ezs() : Int = CanBusNative.getECUParameterB(CanBAddrs.EZS_A4, 32, 24)
	
	
}
