package com.rndash.mbheadunit.nativeCan.canB


import com.rndash.mbheadunit.nativeCan.CanBAddrs
import com.rndash.mbheadunit.nativeCan.CanBusNative



/**
 *    GENERATED BY parse_kt.py
 *    Decoder class for ECU Frame EZS_A6 (ID: 0x001E)
**/
object EZS_A6 {

	/** year specification **/
	fun get_ver_jahr() : Int = getParam(1, 5)

	/** change year **/
	fun get_ver_ae() : Int = getParam(6, 2)

	/** Tire pressure modules available **/
	fun get_tpm_vh() : Int = getParam(30, 2)

	override fun toString(): String {
		return """
			VER_JAHR: ${get_ver_jahr()}
			VER_AE: ${get_ver_ae()}
			TPM_VH: ${get_tpm_vh()}
		""".trimIndent()
	}


	private fun getParam(o: Int, l: Int) : Int = CanBusNative.getECUParameterB(CanBAddrs.EZS_A6, o, l)
}
