
@file:Suppress("unused", "FunctionName")
package com.rndash.mbheadunit.nativeCan.canB
import com.rndash.mbheadunit.CanFrame // AUTO GEN
import com.rndash.mbheadunit.nativeCan.CanBusNative // AUTO GEN

/**
 *   Generated by db_converter.py
 *   Object for EZS_A7 (ID 0x0003)
**/

object EZS_A7 {

    	/** Gets Brake light switch status **/
	fun get_bls_st() : BLS_ST = when(CanBusNative.getECUParameterB(CanBAddrs.EZS_A7, 6, 2)) {
		 0 -> BLS_ST.BREMSE_NBET
		 1 -> BLS_ST.BREMSE_BET
		 2 -> BLS_ST.NOT_DEFINED
		 3 -> BLS_ST.SNV
		 else -> throw Exception("Invalid raw value for BLS_ST")
	}
	
	/** Sets Brake light switch status **/
	fun set_bls_st(f: CanFrame, p: BLS_ST) = CanBusNative.setFrameParameter(f, 6, 2, p.raw)
	
	/** Gets brake light suppression **/
	fun get_bls_unt() : Boolean = CanBusNative.getECUParameterB(CanBAddrs.EZS_A7, 5, 1) != 0
	
	/** Sets brake light suppression **/
	fun set_bls_unt(f: CanFrame, p: Boolean) = CanBusNative.setFrameParameter(f, 5, 1, if(p) 1 else 0)
	
	/** Gets switch on additional water pump **/
	fun get_zwp_ein_ms() : Boolean = CanBusNative.getECUParameterB(CanBAddrs.EZS_A7, 4, 1) != 0
	
	/** Sets switch on additional water pump **/
	fun set_zwp_ein_ms(f: CanFrame, p: Boolean) = CanBusNative.setFrameParameter(f, 4, 1, if(p) 1 else 0)
	
	/** Gets motor fan defective control lamp **/
	fun get_lueft_mot_kl() : Boolean = CanBusNative.getECUParameterB(CanBAddrs.EZS_A7, 3, 1) != 0
	
	/** Sets motor fan defective control lamp **/
	fun set_lueft_mot_kl(f: CanFrame, p: Boolean) = CanBusNative.setFrameParameter(f, 3, 1, if(p) 1 else 0)
	
	/** Gets Air conditioning compressor emergency shutdown **/
	fun get_komp_notaus() : Boolean = CanBusNative.getECUParameterB(CanBAddrs.EZS_A7, 2, 1) != 0
	
	/** Sets Air conditioning compressor emergency shutdown **/
	fun set_komp_notaus(f: CanFrame, p: Boolean) = CanBusNative.setFrameParameter(f, 2, 1, if(p) 1 else 0)
	
	/** Gets switch off air conditioning compressor: acceleration **/
	fun get_komp_baus() : Boolean = CanBusNative.getECUParameterB(CanBAddrs.EZS_A7, 1, 1) != 0
	
	/** Sets switch off air conditioning compressor: acceleration **/
	fun set_komp_baus(f: CanFrame, p: Boolean) = CanBusNative.setFrameParameter(f, 1, 1, if(p) 1 else 0)
	
	/** Gets idle is stable **/
	fun get_ll_stbl() : Boolean = CanBusNative.getECUParameterB(CanBAddrs.EZS_A7, 0, 1) != 0
	
	/** Sets idle is stable **/
	fun set_ll_stbl(f: CanFrame, p: Boolean) = CanBusNative.setFrameParameter(f, 0, 1, if(p) 1 else 0)
	
	/** Gets gear selector lever position (only NAG) **/
	fun get_whc() : WHC = when(CanBusNative.getECUParameterB(CanBAddrs.EZS_A7, 12, 4)) {
		 5 -> WHC.D
		 6 -> WHC.N
		 7 -> WHC.R
		 8 -> WHC.P
		 9 -> WHC.PLUS
		 10 -> WHC.MINUS
		 11 -> WHC.N_ZW_D
		 12 -> WHC.R_ZW_N
		 13 -> WHC.P_ZW_R
		 15 -> WHC.SNV
		 else -> throw Exception("Invalid raw value for WHC")
	}
	
	/** Sets gear selector lever position (only NAG) **/
	fun set_whc(f: CanFrame, p: WHC) = CanBusNative.setFrameParameter(f, 12, 4, p.raw)
	
	/** Gets Status of heating output **/
	fun get_hzl_st() : HZL_ST = when(CanBusNative.getECUParameterB(CanBAddrs.EZS_A7, 10, 2)) {
		 0 -> HZL_ST.HEATER_SHUT_OFF_VALVE_IS_CLOSED
		 1 -> HZL_ST.OPEN
		 2 -> HZL_ST.TAKT
		 3 -> HZL_ST.SNV
		 else -> throw Exception("Invalid raw value for HZL_ST")
	}
	
	/** Sets Status of heating output **/
	fun set_hzl_st(f: CanFrame, p: HZL_ST) = CanBusNative.setFrameParameter(f, 10, 2, p.raw)
	
	/** Gets Parking position engaged **/
	fun get_p() : Boolean = CanBusNative.getECUParameterB(CanBAddrs.EZS_A7, 9, 1) != 0
	
	/** Sets Parking position engaged **/
	fun set_p(f: CanFrame, p: Boolean) = CanBusNative.setFrameParameter(f, 9, 1, if(p) 1 else 0)
	
	/** Gets reverse gear engaged (all transmissions) **/
	fun get_rg() : Boolean = CanBusNative.getECUParameterB(CanBAddrs.EZS_A7, 8, 1) != 0
	
	/** Sets reverse gear engaged (all transmissions) **/
	fun set_rg(f: CanFrame, p: Boolean) = CanBusNative.setFrameParameter(f, 8, 1, if(p) 1 else 0)
	
	/** Gets direction of rotation of front left wheel **/
	fun get_drtgvl() : DRTGVL = when(CanBusNative.getECUParameterB(CanBAddrs.EZS_A7, 16, 2)) {
		 0 -> DRTGVL.PASSIVE
		 1 -> DRTGVL.FORWARD
		 2 -> DRTGVL.REVERSE
		 3 -> DRTGVL.SNV
		 else -> throw Exception("Invalid raw value for DRTGVL")
	}
	
	/** Sets direction of rotation of front left wheel **/
	fun set_drtgvl(f: CanFrame, p: DRTGVL) = CanBusNative.setFrameParameter(f, 16, 2, p.raw)
	
	/** Gets wheel speed front left UNIT: 1 / min **/
	fun get_dvl() : Int = CanBusNative.getECUParameterB(CanBAddrs.EZS_A7, 18, 14)
	
	/** Sets wheel speed front left UNIT: 1 / min **/
	fun set_dvl(f: CanFrame, p: Int) = CanBusNative.setFrameParameter(f, 18, 14, p)
	
	/** Gets clutch pressed **/
	fun get_kpl() : Boolean = CanBusNative.getECUParameterB(CanBAddrs.EZS_A7, 39, 1) != 0
	
	/** Sets clutch pressed **/
	fun set_kpl(f: CanFrame, p: Boolean) = CanBusNative.setFrameParameter(f, 39, 1, if(p) 1 else 0)
	
	/** Gets engine oil temperature too high (overheating) **/
	fun get_uehitz() : Boolean = CanBusNative.getECUParameterB(CanBAddrs.EZS_A7, 38, 1) != 0
	
	/** Sets engine oil temperature too high (overheating) **/
	fun set_uehitz(f: CanFrame, p: Boolean) = CanBusNative.setFrameParameter(f, 38, 1, if(p) 1 else 0)
	
	/** Gets Brake pad wear indicator lamp **/
	fun get_bbv_kl() : Boolean = CanBusNative.getECUParameterB(CanBAddrs.EZS_A7, 37, 1) != 0
	
	/** Sets Brake pad wear indicator lamp **/
	fun set_bbv_kl(f: CanFrame, p: Boolean) = CanBusNative.setFrameParameter(f, 37, 1, if(p) 1 else 0)
	
	/** Gets ABS defective control lamp **/
	fun get_abs_kl() : Boolean = CanBusNative.getECUParameterB(CanBAddrs.EZS_A7, 36, 1) != 0
	
	/** Sets ABS defective control lamp **/
	fun set_abs_kl(f: CanFrame, p: Boolean) = CanBusNative.setFrameParameter(f, 36, 1, if(p) 1 else 0)
	
	/** Gets ESP defective control lamp **/
	fun get_esp_kl() : Boolean = CanBusNative.getECUParameterB(CanBAddrs.EZS_A7, 35, 1) != 0
	
	/** Sets ESP defective control lamp **/
	fun set_esp_kl(f: CanFrame, p: Boolean) = CanBusNative.setFrameParameter(f, 35, 1, if(p) 1 else 0)
	
	/** Gets BAS defective control lamp **/
	fun get_bas_kl() : Boolean = CanBusNative.getECUParameterB(CanBAddrs.EZS_A7, 34, 1) != 0
	
	/** Sets BAS defective control lamp **/
	fun set_bas_kl(f: CanFrame, p: Boolean) = CanBusNative.setFrameParameter(f, 34, 1, if(p) 1 else 0)
	
	/** Gets Diagnostic control lamp (OBD II) **/
	fun get_diag_kl() : Boolean = CanBusNative.getECUParameterB(CanBAddrs.EZS_A7, 33, 1) != 0
	
	/** Sets Diagnostic control lamp (OBD II) **/
	fun set_diag_kl(f: CanFrame, p: Boolean) = CanBusNative.setFrameParameter(f, 33, 1, if(p) 1 else 0)
	
	/** Gets Oil level / oil pressure control lamp **/
	fun get_oel_kl() : Boolean = CanBusNative.getECUParameterB(CanBAddrs.EZS_A7, 32, 1) != 0
	
	/** Sets Oil level / oil pressure control lamp **/
	fun set_oel_kl(f: CanFrame, p: Boolean) = CanBusNative.setFrameParameter(f, 32, 1, if(p) 1 else 0)
	
	/** Gets Substitution of right low beam **/
	fun get_sub_abl_r() : Boolean = CanBusNative.getECUParameterB(CanBAddrs.EZS_A7, 46, 1) != 0
	
	/** Sets Substitution of right low beam **/
	fun set_sub_abl_r(f: CanFrame, p: Boolean) = CanBusNative.setFrameParameter(f, 46, 1, if(p) 1 else 0)
	
	/** Gets Substitution of left low beam **/
	fun get_sub_abl_l() : Boolean = CanBusNative.getECUParameterB(CanBAddrs.EZS_A7, 45, 1) != 0
	
	/** Sets Substitution of left low beam **/
	fun set_sub_abl_l(f: CanFrame, p: Boolean) = CanBusNative.setFrameParameter(f, 45, 1, if(p) 1 else 0)
	
	/** Gets ART distance warning is switched on **/
	fun get_art_abw_akt() : Boolean = CanBusNative.getECUParameterB(CanBAddrs.EZS_A7, 44, 1) != 0
	
	/** Sets ART distance warning is switched on **/
	fun set_art_abw_akt(f: CanFrame, p: Boolean) = CanBusNative.setFrameParameter(f, 44, 1, if(p) 1 else 0)
	
	/** Gets emergency braking (brake light flashing) **/
	fun get_notbre() : Boolean = CanBusNative.getECUParameterB(CanBAddrs.EZS_A7, 43, 1) != 0
	
	/** Sets emergency braking (brake light flashing) **/
	fun set_notbre(f: CanFrame, p: Boolean) = CanBusNative.setFrameParameter(f, 43, 1, if(p) 1 else 0)
	
	/** Gets Gear selector lever position (NAG, KSG, CVT) **/
	fun get_whst() : WHST = when(CanBusNative.getECUParameterB(CanBAddrs.EZS_A7, 40, 3)) {
		 0 -> WHST.P
		 1 -> WHST.R
		 2 -> WHST.N
		 4 -> WHST.D
		 7 -> WHST.SNV
		 else -> throw Exception("Invalid raw value for WHST")
	}
	
	/** Sets Gear selector lever position (NAG, KSG, CVT) **/
	fun set_whst(f: CanFrame, p: WHST) = CanBusNative.setFrameParameter(f, 40, 3, p.raw)
	
	
}
