package com.rndash.mbheadunit.nativeCan.canB


import com.rndash.mbheadunit.nativeCan.CanBAddrs
import com.rndash.mbheadunit.nativeCan.CanBusNative



/**
 *    GENERATED BY parse_kt.py
 *    Decoder class for ECU Frame EZS_A10 (ID: 0x010A)
**/
object EZS_A10 {

	/** (Impulse) (Pulses) pulse ring counter left rear wheel (48 per revolution) **/
	fun get_riz_hl() : Int = getParam(0, 8)

	/** (Impulse) (Pulses) pulse ring counter right rear wheel (48 per revolution) **/
	fun get_riz_hr() : Int = getParam(8, 8)

	/** Direction of rotation right rear wheel **/
	fun get_drtghr() : Int = getParam(16, 2)

	/** (1/min) (1 / min), rear right wheel speed **/
	fun get_dhr() : Int = getParam(18, 14)

	/** Rotation direction left rear wheel **/
	fun get_drtghl() : Int = getParam(32, 2)

	/** (1/min) (1 / min), rear left wheel speed **/
	fun get_dhl() : Int = getParam(34, 14)

	override fun toString(): String {
		return """
			RIZ_HL: ${get_riz_hl()}
			RIZ_HR: ${get_riz_hr()}
			DRTGHR: ${get_drtghr()}
			DHR: ${get_dhr()}
			DRTGHL: ${get_drtghl()}
			DHL: ${get_dhl()}
		""".trimIndent()
	}


	private fun getParam(o: Int, l: Int) : Int = CanBusNative.getECUParameterB(CanBAddrs.EZS_A10, o, l)
}
