
package com.rndash.mbheadunit.nativeCan.canB

import com.rndash.mbheadunit.nativeCan.CanBusNative // AUTO GEN

/**
 *   Generated by db_converter.py
 *   Object for EZS_A8 (ID 0x0390)
**/

object EZS_A8 {

    	/** Gets refrigerant level control inactive **/
	fun get_kfk_aus() : Boolean = CanBusNative.getECUParameterB(CanBAddrs.EZS_A8, 7, 1) != 0
	
	/** Gets Corrosive gas-dependent air recirculation switch off **/
	fun get_sus_aus() : Boolean = CanBusNative.getECUParameterB(CanBAddrs.EZS_A8, 6, 1) != 0
	
	/** Gets Corrosive gas-dependent recirculation switch generally on **/
	fun get_sus_ein() : Boolean = CanBusNative.getECUParameterB(CanBAddrs.EZS_A8, 5, 1) != 0
	
	/** Gets 40% basic ventilation **/
	fun get_gbl_40() : Boolean = CanBusNative.getECUParameterB(CanBAddrs.EZS_A8, 4, 1) != 0
	
	/** Gets Fan bar display only in manual mode **/
	fun get_gba_man() : Boolean = CanBusNative.getECUParameterB(CanBAddrs.EZS_A8, 3, 1) != 0
	
	/** Gets always REHEAT operation **/
	fun get_rht_ein() : Boolean = CanBusNative.getECUParameterB(CanBAddrs.EZS_A8, 2, 1) != 0
	
	/** Gets manual recirculation switching for an unlimited period **/
	fun get_umluft_ubg() : Boolean = CanBusNative.getECUParameterB(CanBAddrs.EZS_A8, 1, 1) != 0
	
	/** Gets additional water pump not installed **/
	fun get_zwp_nvh() : Boolean = CanBusNative.getECUParameterB(CanBAddrs.EZS_A8, 0, 1) != 0
	
	/** Gets "-1 ° C" hot countries **/
	fun get_heissland_1() : Boolean = CanBusNative.getECUParameterB(CanBAddrs.EZS_A8, 15, 1) != 0
	
	/** Gets Solar influence not active **/
	fun get_sol_aus() : Boolean = CanBusNative.getECUParameterB(CanBAddrs.EZS_A8, 14, 1) != 0
	
	/** Gets Recirculation flap open in OFF operation **/
	fun get_umluft_aus() : Boolean = CanBusNative.getECUParameterB(CanBAddrs.EZS_A8, 13, 1) != 0
	
	/** Gets 20% basic ventilation E-suction fan on **/
	fun get_esaugbel_ein() : Boolean = CanBusNative.getECUParameterB(CanBAddrs.EZS_A8, 12, 1) != 0
	
	/** Gets Completely close the recirculation flap from <20% **/
	fun get_circulation_on() : Boolean = CanBusNative.getECUParameterB(CanBAddrs.EZS_A8, 11, 1) != 0
	
	/** Gets "+ 2 ° C" increase **/
	fun get_kaltland_2() : Boolean = CanBusNative.getECUParameterB(CanBAddrs.EZS_A8, 10, 1) != 0
	
	/** Gets "- 2 ° C" reduction **/
	fun get_heissland_2() : Boolean = CanBusNative.getECUParameterB(CanBAddrs.EZS_A8, 9, 1) != 0
	
	/** Gets "+ 1 ° C" increase **/
	fun get_kaltland_1() : Boolean = CanBusNative.getECUParameterB(CanBAddrs.EZS_A8, 8, 1) != 0
	
	/** Gets pressure characteristic **/
	fun get_p_knl() : P_KNL = when(CanBusNative.getECUParameterB(CanBAddrs.EZS_A8, 20, 4)) {
		 0 -> P_KNL.P_KNL0
		 1 -> P_KNL.P_KNL1
		 2 -> P_KNL.P_KNL2
		 3 -> P_KNL.P_KNL3
		 4 -> P_KNL.P_KNL4
		 15 -> P_KNL.SNV
		 else -> throw Exception("Invalid raw value for P_KNL")
	}
	
	/** Gets basic ventilation characteristic **/
	fun get_gbl_knl() : GBL_KNL = when(CanBusNative.getECUParameterB(CanBAddrs.EZS_A8, 17, 3)) {
		 0 -> GBL_KNL.GBL_KNL0
		 1 -> GBL_KNL.GBL_KNL1
		 2 -> GBL_KNL.GBL_KNL2
		 7 -> GBL_KNL.SNV
		 else -> throw Exception("Invalid raw value for GBL_KNL")
	}
	
	/** Gets desert lands with sand **/
	fun get_desert_country() : Boolean = CanBusNative.getECUParameterB(CanBAddrs.EZS_A8, 16, 1) != 0
	
	/** Gets Autom. Standard logic fan **/
	fun get_asl_gbl() : Boolean = CanBusNative.getECUParameterB(CanBAddrs.EZS_A8, 31, 1) != 0
	
	/** Gets Autom. Standard logic air distribution **/
	fun get_asl_lvt() : Boolean = CanBusNative.getECUParameterB(CanBAddrs.EZS_A8, 30, 1) != 0
	
	/** Gets "MAXCOOL" display (USA only) **/
	fun get_maxcool() : Boolean = CanBusNative.getECUParameterB(CanBAddrs.EZS_A8, 29, 1) != 0
	
	/** Gets residual heat utilization available **/
	fun get_rest_vh() : Boolean = CanBusNative.getECUParameterB(CanBAddrs.EZS_A8, 28, 1) != 0
	
	/** Gets Inside sensor available in DBE **/
	fun get_ifdbe_vh() : Boolean = CanBusNative.getECUParameterB(CanBAddrs.EZS_A8, 27, 1) != 0
	
	/** Gets dew point sensor not available **/
	fun get_tps_nvh() : Boolean = CanBusNative.getECUParameterB(CanBAddrs.EZS_A8, 26, 1) != 0
	
	/** Gets Gear shift point increase in case of heating power deficit **/
	fun get_gspa_kla_heiz() : Boolean = CanBusNative.getECUParameterB(CanBAddrs.EZS_A8, 25, 1) != 0
	
	/** Gets Gear shift point increase in case of cooling power deficit **/
	fun get_gspa_kla_kuehl() : Boolean = CanBusNative.getECUParameterB(CanBAddrs.EZS_A8, 24, 1) != 0
	
	
}
