package com.rndash.mbheadunit.nativeCan.canB


import com.rndash.mbheadunit.nativeCan.CanBAddrs
import com.rndash.mbheadunit.nativeCan.CanBusNative



/**
 *    GENERATED BY parse_kt.py
 *    Decoder class for ECU Frame EZS_A11 (ID: 0x0016)
**/
object EZS_A11 {

	/** (V) Batteriespannung **/
	fun get_u_batt() : Int = getParam(0, 8)

	override fun toString(): String {
		return """
			U_BATT: ${get_u_batt()}
		""".trimIndent()
	}


	private fun getParam(o: Int, l: Int) : Int = CanBusNative.getECUParameterB(CanBAddrs.EZS_A11, o, l)
}
