
package com.rndash.mbheadunit.nativeCan.canB

import com.rndash.mbheadunit.nativeCan.CanBusNative // AUTO GEN

/**
 *   Generated by db_converter.py
 *   Object for EZS_A6 (ID 0x001E)
**/

object EZS_A6 {

    	/** Gets year of change **/
	fun get_ver_ae() : VER_AE = when(CanBusNative.getECUParameterB(CanBAddrs.EZS_A6, 6, 2)) {
		 0 -> VER_AE.AE1
		 1 -> VER_AE.AEX
		 2 -> VER_AE.AE2
		 3 -> VER_AE.SB
		 else -> throw Exception("Invalid raw value for VER_AE")
	}
	
	/** Gets year specification **/
	fun get_ver_jahr() : VER_JAHR = when(CanBusNative.getECUParameterB(CanBAddrs.EZS_A6, 1, 5)) {
		 0 -> VER_JAHR.YEAR00
		 1 -> VER_JAHR.YEAR01
		 29 -> VER_JAHR.YEAR29
		 30 -> VER_JAHR.N_DEF
		 31 -> VER_JAHR.SB
		 else -> throw Exception("Invalid raw value for VER_JAHR")
	}
	
	/** Gets Tire pressure module available **/
	fun get_tpm_vh() : TPM_VH = when(CanBusNative.getECUParameterB(CanBAddrs.EZS_A6, 30, 2)) {
		 0 -> TPM_VH.NO_TPM
		 1 -> TPM_VH.LOWLINE
		 2 -> TPM_VH.MIDLINE
		 3 -> TPM_VH.SNV
		 else -> throw Exception("Invalid raw value for TPM_VH")
	}
	
	
}
