
package com.rndash.mbheadunit.nativeCan.canB

import com.rndash.mbheadunit.nativeCan.CanBusNative // AUTO GEN

/**
 *   Generated by db_converter.py
 *   Object for EZS_A2 (ID 0x0002)
**/

object EZS_A2 {

    	/** Gets Pulse ring counter, front left wheel (48 per revolution) UNIT: Pulse **/
	fun get_riz_vl() : Int = CanBusNative.getECUParameterB(CanBAddrs.EZS_A2, 0, 8)
	
	/** Gets Pulse ring counter, front right wheel (48 per revolution) UNIT: Pulse **/
	fun get_riz_vr() : Int = CanBusNative.getECUParameterB(CanBAddrs.EZS_A2, 8, 8)
	
	/** Gets Motor speed UNIT: 1 / min **/
	fun get_n_mot() : Int = CanBusNative.getECUParameterB(CanBAddrs.EZS_A2, 16, 16)
	
	/** Gets engine coolant temperature UNIT: ° C **/
	fun get_t_mot() : Int = CanBusNative.getECUParameterB(CanBAddrs.EZS_A2, 32, 8)
	
	
}
