
@file:Suppress("unused", "FunctionName", "ClassName")
package com.rndash.mbheadunit.nativeCan.canB
import com.rndash.mbheadunit.CanFrame // AUTO GEN
import com.rndash.mbheadunit.nativeCan.CanBusNative // AUTO GEN

/**
 *   Generated by db_converter.py
 *   Object for GPS_A2 (ID 0x0339)
**/

object GPS_A2 {

    /** 
     *  Returns the most recent Can Frame representing the state
     *  of GPS_A2
    **/
    fun get_frame() : CanFrame? = CanBusNative.getBFrame(CanBAddrs.GPS_A2)

	/** Gets UTC years  **/
	fun get_utc_years() : Int = CanBusNative.getECUParameterB(CanBAddrs.GPS_A2, 0, 16)
	
	/** Sets UTC years  **/
	fun set_utc_years(f: CanFrame, p: Int) : CanFrame? {
		checkFrame(f)
		return CanBusNative.setFrameParameter(f, 0, 16, p)
	}
	
	/** Gets UTC months  **/
	fun get_utc_months() : Int = CanBusNative.getECUParameterB(CanBAddrs.GPS_A2, 16, 8)
	
	/** Sets UTC months  **/
	fun set_utc_months(f: CanFrame, p: Int) : CanFrame? {
		checkFrame(f)
		return CanBusNative.setFrameParameter(f, 16, 8, p)
	}
	
	/** Gets UTC days  **/
	fun get_utc_days() : Int = CanBusNative.getECUParameterB(CanBAddrs.GPS_A2, 24, 8)
	
	/** Sets UTC days  **/
	fun set_utc_days(f: CanFrame, p: Int) : CanFrame? {
		checkFrame(f)
		return CanBusNative.setFrameParameter(f, 24, 8, p)
	}
	
	/** Gets UTC hours  **/
	fun get_utc_hours() : Int = CanBusNative.getECUParameterB(CanBAddrs.GPS_A2, 32, 8)
	
	/** Sets UTC hours  **/
	fun set_utc_hours(f: CanFrame, p: Int) : CanFrame? {
		checkFrame(f)
		return CanBusNative.setFrameParameter(f, 32, 8, p)
	}
	
	/** Gets UTC minutes  **/
	fun get_utc_minutes() : Int = CanBusNative.getECUParameterB(CanBAddrs.GPS_A2, 40, 8)
	
	/** Sets UTC minutes  **/
	fun set_utc_minutes(f: CanFrame, p: Int) : CanFrame? {
		checkFrame(f)
		return CanBusNative.setFrameParameter(f, 40, 8, p)
	}
	
	/** Gets UTC seconds  **/
	fun get_utc_seconds() : Int = CanBusNative.getECUParameterB(CanBAddrs.GPS_A2, 48, 16)
	
	/** Sets UTC seconds  **/
	fun set_utc_seconds(f: CanFrame, p: Int) : CanFrame? {
		checkFrame(f)
		return CanBusNative.setFrameParameter(f, 48, 16, p)
	}
	
	/**
     * Auto generated function
     * Throws exception if user tries to set a value in a frame
     * Not designated from the correct ECU
    **/
    private fun checkFrame(f: CanFrame) {
        if (f.canID != CanBAddrs.GPS_A2.addr) {
            throw IllegalArgumentException("CAN ID does not match object!")
        }
    }

	override fun toString() = """
		|Frame GPS_A2 (0x0339):
		|	UTC years : ${get_utc_years()} years
		|	UTC months : ${get_utc_months()} months
		|	UTC days : ${get_utc_days()} days
		|	UTC hours : ${get_utc_hours()} h
		|	UTC minutes : ${get_utc_minutes()} min
		|	UTC seconds : ${get_utc_seconds()} s
	""".trimMargin("|")
}
