package com.rndash.mbheadunit.nativeCan.canB


import com.rndash.mbheadunit.nativeCan.CanBAddrs
import com.rndash.mbheadunit.nativeCan.CanBusNative



/**
 *    GENERATED BY parse_kt.py
 *    Decoder class for ECU Frame GPS_A3 (ID: 0x033A)
**/
object GPS_A3 {

	/** (cm/s) (Cm / s) GPS Speed **/
	fun get_gps_speed() : Int = getParam(0, 16)

	/** (°) (°) GPS Heading (0 ° = North) **/
	fun get_gps_heading() : Int = getParam(16, 8)

	/** (m) (M) GPS height **/
	fun get_gps_height() : Int = getParam(24, 8)

	/** GPS fix **/
	fun get_gps_fix() : Int = getParam(37, 3)

	/** GPS position avilable **/
	fun get_pos_avlb() : Boolean = getParam(40, 1) != 0

	/** Differential GPS position data available **/
	fun get_diff_pos_avlb() : Boolean = getParam(41, 1) != 0

	/** Dead reckoning available **/
	fun get_dead_rck() : Boolean = getParam(42, 1) != 0

	/** Inside digitalized area (on map) **/
	fun get_idg() : Boolean = getParam(43, 1) != 0

	/** Fully digitalized area **/
	fun get_fdg() : Boolean = getParam(44, 1) != 0

	/** Matched to digitally map **/
	fun get_mdm() : Boolean = getParam(45, 1) != 0

	/** Calibrated **/
	fun get_cali() : Boolean = getParam(46, 1) != 0

	/** Vertical Dilution Of Position **/
	fun get_v_dop() : Int = getParam(48, 8)

	/** Horizontal Dilution Of Position **/
	fun get_h_dop() : Int = getParam(56, 8)

	override fun toString(): String {
		return """
			GPS_SPEED: ${get_gps_speed()}
			GPS_HEADING: ${get_gps_heading()}
			GPS_HEIGHT: ${get_gps_height()}
			GPS_FIX: ${get_gps_fix()}
			POS_AVLB: ${get_pos_avlb()}
			DIFF_POS_AVLB: ${get_diff_pos_avlb()}
			DEAD_RCK: ${get_dead_rck()}
			IDG: ${get_idg()}
			FDG: ${get_fdg()}
			MDM: ${get_mdm()}
			CALI: ${get_cali()}
			V_DOP: ${get_v_dop()}
			H_DOP: ${get_h_dop()}
		""".trimIndent()
	}


	private fun getParam(o: Int, l: Int) : Int = CanBusNative.getECUParameterB(CanBAddrs.GPS_A3, o, l)
}
