package com.rndash.mbheadunit.nativeCan.canB


import com.rndash.mbheadunit.nativeCan.CanBAddrs
import com.rndash.mbheadunit.nativeCan.CanBusNative



/**
 *    GENERATED BY parse_kt.py
 *    Decoder class for ECU Frame GPS_A2 (ID: 0x0339)
**/
object GPS_A2 {

	/** (years) (Years) UTC years **/
	fun get_utc_years() : Int = getParam(0, 16)

	/** (months) (Months) UTC months **/
	fun get_utc_months() : Int = getParam(16, 8)

	/** (days) (Days) UTC days **/
	fun get_utc_days() : Int = getParam(24, 8)

	/** (h) (H) UTC hours **/
	fun get_utc_hours() : Int = getParam(32, 8)

	/** (min) (Min) UTC minutes **/
	fun get_utc_minutes() : Int = getParam(40, 8)

	/** (s) (S) UTC seconds **/
	fun get_utc_seconds() : Int = getParam(48, 16)

	override fun toString(): String {
		return """
			UTC_YEARS: ${get_utc_years()}
			UTC_MONTHS: ${get_utc_months()}
			UTC_DAYS: ${get_utc_days()}
			UTC_HOURS: ${get_utc_hours()}
			UTC_MINUTES: ${get_utc_minutes()}
			UTC_SECONDS: ${get_utc_seconds()}
		""".trimIndent()
	}


	private fun getParam(o: Int, l: Int) : Int = CanBusNative.getECUParameterB(CanBAddrs.GPS_A2, o, l)
}
