package com.rndash.mbheadunit.nativeCan.canB


import com.rndash.mbheadunit.nativeCan.CanBAddrs
import com.rndash.mbheadunit.nativeCan.CanBusNative



/**
 *    GENERATED BY parse_kt.py
 *    Decoder class for ECU Frame HFS_A1 (ID: 0x0078)
**/
object HFS_A1 {

	/** Status tailgate **/
	fun get_hd_st() : Int = getParam(0, 3)

	/** Close rear lid and secure actuated **/
	fun get_hd_sich_hfs() : Boolean = getParam(3, 1) != 0

	override fun toString(): String {
		return """
			HD_ST: ${get_hd_st()}
			HD_SICH_HFS: ${get_hd_sich_hfs()}
		""".trimIndent()
	}


	private fun getParam(o: Int, l: Int) : Int = CanBusNative.getECUParameterB(CanBAddrs.HFS_A1, o, l)
}
