package com.rndash.mbheadunit.nativeCan.canB


import com.rndash.mbheadunit.nativeCan.CanBAddrs
import com.rndash.mbheadunit.nativeCan.CanBusNative



/**
 *    GENERATED BY parse_kt.py
 *    Decoder class for ECU Frame KG_A1 (ID: 0x01B2)
**/
object KG_A1 {

	/** Messg. 5: "selector lever in P please od N position." **/
	fun get_m5() : Boolean = getParam(0, 1) != 0

	/** Messg. 4: "Check chip card / key battery" (white) **/
	fun get_m4() : Boolean = getParam(1, 1) != 0

	/** Messg. 3: "selector lever to the P" (red tone) **/
	fun get_m3() : Boolean = getParam(2, 1) != 0

	/** Messg. 2 "/ recognized chip card keys in the vehicle" (white) **/
	fun get_m2() : Boolean = getParam(3, 1) != 0

	/** Messg. 1 "/ not recognized chip card key" (White) **/
	fun get_m1() : Boolean = getParam(4, 1) != 0

	/** Messg. 0 "chip card / key is not recognized" (red) **/
	fun get_m0() : Boolean = getParam(5, 1) != 0

	/** switch on warning **/
	fun get_warnton_kg() : Boolean = getParam(6, 1) != 0

	/** Messg. "Take chip card / key!": 12 **/
	fun get_m12() : Boolean = getParam(9, 1) != 0

	/** Messg. "Please leave keys stuck": 11 **/
	fun get_m11() : Boolean = getParam(10, 1) != 0

	/** Messg. 10: "Key anticipates" **/
	fun get_m10() : Boolean = getParam(11, 1) != 0

	/** Messg. 9: "Keyless Go in diagnosis" **/
	fun get_m9() : Boolean = getParam(12, 1) != 0

	/** Messg. 8: "Door open" **/
	fun get_m8() : Boolean = getParam(13, 1) != 0

	/** Messg. 7: Reserved **/
	fun get_m7() : Boolean = getParam(14, 1) != 0

	/** Messg. 6: "No driver authorization" **/
	fun get_m6() : Boolean = getParam(15, 1) != 0

	/** (km) (Km) way indication Keyless Go **/
	fun get_km_rest_kg() : Int = getParam(16, 8)

	override fun toString(): String {
		return """
			M5: ${get_m5()}
			M4: ${get_m4()}
			M3: ${get_m3()}
			M2: ${get_m2()}
			M1: ${get_m1()}
			M0: ${get_m0()}
			WARNTON_KG: ${get_warnton_kg()}
			M12: ${get_m12()}
			M11: ${get_m11()}
			M10: ${get_m10()}
			M9: ${get_m9()}
			M8: ${get_m8()}
			M7: ${get_m7()}
			M6: ${get_m6()}
			KM_REST_KG: ${get_km_rest_kg()}
		""".trimIndent()
	}


	private fun getParam(o: Int, l: Int) : Int = CanBusNative.getECUParameterB(CanBAddrs.KG_A1, o, l)
}
