package com.rndash.mbheadunit.nativeCan.canB


import com.rndash.mbheadunit.nativeCan.CanBAddrs
import com.rndash.mbheadunit.nativeCan.CanBusNative



/**
 *    GENERATED BY parse_kt.py
 *    Decoder class for ECU Frame KLA_A3 (ID: 0x00F1)
**/
object KLA_A3 {

	/** (%) (%) Heating power requirement **/
	fun get_hzl_anf() : Int = getParam(0, 8)

	/** (°C) (° C) Outside air temperature for heat management **/
	fun get_t_aussen_wm() : Int = getParam(8, 8)

	override fun toString(): String {
		return """
			HZL_ANF: ${get_hzl_anf()}
			T_AUSSEN_WM: ${get_t_aussen_wm()}
		""".trimIndent()
	}


	private fun getParam(o: Int, l: Int) : Int = CanBusNative.getECUParameterB(CanBAddrs.KLA_A3, o, l)
}
