
package com.rndash.mbheadunit.nativeCan.canB

import com.rndash.mbheadunit.nativeCan.CanBusNative // AUTO GEN

/**
 *   Generated by db_converter.py
 *   Object for KLA_A1 (ID 0x0030)
**/

object KLA_A1 {

    	/** Gets Ventilate auxiliary heating **/
	fun get_ventilate() : Boolean = CanBusNative.getECUParameterB(CanBAddrs.KLA_A1, 7, 1) != 0
	
	/** Gets heating auxiliary heating **/
	fun get_heating() : Boolean = CanBusNative.getECUParameterB(CanBAddrs.KLA_A1, 6, 1) != 0
	
	/** Gets Idle speed increase to increase the cooling capacity **/
	fun get_ll_dza() : Boolean = CanBusNative.getECUParameterB(CanBAddrs.KLA_A1, 5, 1) != 0
	
	/** Gets Switching on auxiliary heater allowed **/
	fun get_zh_ein_ok() : Boolean = CanBusNative.getECUParameterB(CanBAddrs.KLA_A1, 4, 1) != 0
	
	/** Gets switch on additional water pump **/
	fun get_zwp_ein() : Boolean = CanBusNative.getECUParameterB(CanBAddrs.KLA_A1, 3, 1) != 0
	
	/** Gets switch on the indoor sensor fan **/
	fun get_ifg_ein() : Boolean = CanBusNative.getECUParameterB(CanBAddrs.KLA_A1, 2, 1) != 0
	
	/** Gets EC mode active **/
	fun get_ec_akt() : Boolean = CanBusNative.getECUParameterB(CanBAddrs.KLA_A1, 1, 1) != 0
	
	/** Gets Switch on the heated rear window **/
	fun get_hhs_ein() : Boolean = CanBusNative.getECUParameterB(CanBAddrs.KLA_A1, 0, 1) != 0
	
	/** Gets Motor fan setpoint speed UNIT:% **/
	fun get_nlfts() : Int = CanBusNative.getECUParameterB(CanBAddrs.KLA_A1, 8, 8)
	
	/** Gets Torque absorption refrigeration compressor UNIT: Nm **/
	fun get_m_komp() : Int = CanBusNative.getECUParameterB(CanBAddrs.KLA_A1, 16, 8)
	
	/** Gets Cooling compressor control signal UNIT:% **/
	fun get_komp_stell() : Int = CanBusNative.getECUParameterB(CanBAddrs.KLA_A1, 24, 8)
	
	/** Gets Switching point increase in case of cooling power deficit **/
	fun get_g_anf_kuehl_kla() : Boolean = CanBusNative.getECUParameterB(CanBAddrs.KLA_A1, 33, 1) != 0
	
	/** Gets windshield heater. switch on (for G463) **/
	fun get_fsb_hzg_ein() : Boolean = CanBusNative.getECUParameterB(CanBAddrs.KLA_A1, 32, 1) != 0
	
	/** Gets Fan output UNIT:% **/
	fun get_geb_lstg() : Int = CanBusNative.getECUParameterB(CanBAddrs.KLA_A1, 40, 8)
	
	/** Gets position ventilation flap down **/
	fun get_lku_vorn() : LKU_VORN = when(CanBusNative.getECUParameterB(CanBAddrs.KLA_A1, 54, 2)) {
		 0 -> LKU_VORN.CENTER
		 1 -> LKU_VORN.UP
		 2 -> LKU_VORN.closed
		 3 -> LKU_VORN.SNV
		 else -> throw Exception("Invalid raw value for LKU_VORN")
	}
	
	/** Gets Position ventilation flap center **/
	fun get_lkm_vorn() : LKM_VORN = when(CanBusNative.getECUParameterB(CanBAddrs.KLA_A1, 52, 2)) {
		 0 -> LKM_VORN.CENTER
		 1 -> LKM_VORN.UP
		 2 -> LKM_VORN.closed
		 3 -> LKM_VORN.SNV
		 else -> throw Exception("Invalid raw value for LKM_VORN")
	}
	
	/** Gets position ventilation flap up **/
	fun get_lko_vorn() : LKO_VORN = when(CanBusNative.getECUParameterB(CanBAddrs.KLA_A1, 50, 2)) {
		 0 -> LKO_VORN.CENTER
		 1 -> LKO_VORN.UP
		 2 -> LKO_VORN.closed
		 3 -> LKO_VORN.SNV
		 else -> throw Exception("Invalid raw value for LKO_VORN")
	}
	
	/** Gets Switching point increase in case of heating power deficit **/
	fun get_g_anf_kla() : Boolean = CanBusNative.getECUParameterB(CanBAddrs.KLA_A1, 49, 1) != 0
	
	/** Gets circulating air active **/
	fun get_ul_akt_kla() : Boolean = CanBusNative.getECUParameterB(CanBAddrs.KLA_A1, 48, 1) != 0
	
	/** Gets Inside temperature UNIT: ° C **/
	fun get_t_innen_kla() : Int = CanBusNative.getECUParameterB(CanBAddrs.KLA_A1, 56, 8)
	
	
}
