
package com.rndash.mbheadunit.nativeCan.canB

import com.rndash.mbheadunit.nativeCan.CanBusNative // AUTO GEN

/**
 *   Generated by db_converter.py
 *   Object for KOMBI_A5 (ID 0x01CA)
**/

object KOMBI_A5 {

    	/** Gets Status combi **/
	fun get_ki_stat() : KI_STAT = when(CanBusNative.getECUParameterB(CanBAddrs.KOMBI_A5, 0, 8)) {
		 0 -> KI_STAT.RESERVED
		 1 -> KI_STAT.RESERVED_1
		 2 -> KI_STAT.NEUTRAL
		 3 -> KI_STAT.AUDIO
		 4 -> KI_STAT.NAVI
		 5 -> KI_STAT.TEL
		 6 -> KI_STAT.NEW_SER
		 19 -> KI_STAT.SPR_FNK_DLG_CLO
		 20 -> KI_STAT.DAT_FNK_DLG_CLO
		 21 -> KI_STAT.SPR_FNK_DLG_OPN
		 22 -> KI_STAT.DAT_FNK_DLG_OPN
		 255 -> KI_STAT.SNV
		 else -> throw Exception("Invalid raw value for KI_STAT")
	}
	
	/** Gets Next display **/
	fun get_button_1_1() : Boolean = CanBusNative.getECUParameterB(CanBAddrs.KOMBI_A5, 15, 1) != 0
	
	/** Gets Previous display **/
	fun get_button_1_2() : Boolean = CanBusNative.getECUParameterB(CanBAddrs.KOMBI_A5, 14, 1) != 0
	
	/** Gets reserve **/
	fun get_button_2_1() : Boolean = CanBusNative.getECUParameterB(CanBAddrs.KOMBI_A5, 13, 1) != 0
	
	/** Gets reserve **/
	fun get_button_2_2() : Boolean = CanBusNative.getECUParameterB(CanBAddrs.KOMBI_A5, 12, 1) != 0
	
	/** Gets "+" button **/
	fun get_button_3_1() : Boolean = CanBusNative.getECUParameterB(CanBAddrs.KOMBI_A5, 11, 1) != 0
	
	/** Gets button "-" **/
	fun get_button_3_2() : Boolean = CanBusNative.getECUParameterB(CanBAddrs.KOMBI_A5, 10, 1) != 0
	
	/** Gets Telephone send **/
	fun get_button_4_1() : Boolean = CanBusNative.getECUParameterB(CanBAddrs.KOMBI_A5, 9, 1) != 0
	
	/** Gets Telephone End **/
	fun get_button_4_2() : Boolean = CanBusNative.getECUParameterB(CanBAddrs.KOMBI_A5, 8, 1) != 0
	
	/** Gets reserve **/
	fun get_button_5_1() : Boolean = CanBusNative.getECUParameterB(CanBAddrs.KOMBI_A5, 23, 1) != 0
	
	/** Gets reserve **/
	fun get_button_5_2() : Boolean = CanBusNative.getECUParameterB(CanBAddrs.KOMBI_A5, 22, 1) != 0
	
	/** Gets reserve **/
	fun get_button_6_1() : Boolean = CanBusNative.getECUParameterB(CanBAddrs.KOMBI_A5, 21, 1) != 0
	
	/** Gets reserve **/
	fun get_button_6_2() : Boolean = CanBusNative.getECUParameterB(CanBAddrs.KOMBI_A5, 20, 1) != 0
	
	/** Gets reserve **/
	fun get_button_7_1() : Boolean = CanBusNative.getECUParameterB(CanBAddrs.KOMBI_A5, 19, 1) != 0
	
	/** Gets reserve **/
	fun get_button_7_2() : Boolean = CanBusNative.getECUParameterB(CanBAddrs.KOMBI_A5, 18, 1) != 0
	
	/** Gets reserve **/
	fun get_button_8_1() : Boolean = CanBusNative.getECUParameterB(CanBAddrs.KOMBI_A5, 17, 1) != 0
	
	/** Gets reserve **/
	fun get_button_8_2() : Boolean = CanBusNative.getECUParameterB(CanBAddrs.KOMBI_A5, 16, 1) != 0
	
	/** Gets Activate Linguatronic **/
	fun get_ptt_1_1() : Boolean = CanBusNative.getECUParameterB(CanBAddrs.KOMBI_A5, 31, 1) != 0
	
	/** Gets Deactivate Linguatronic **/
	fun get_ptt_1_2() : Boolean = CanBusNative.getECUParameterB(CanBAddrs.KOMBI_A5, 30, 1) != 0
	
	/** Gets reserve **/
	fun get_ptt_2_1() : Boolean = CanBusNative.getECUParameterB(CanBAddrs.KOMBI_A5, 29, 1) != 0
	
	/** Gets reserve **/
	fun get_ptt_2_2() : Boolean = CanBusNative.getECUParameterB(CanBAddrs.KOMBI_A5, 28, 1) != 0
	
	/** Gets reserve **/
	fun get_ptt_3_1() : Boolean = CanBusNative.getECUParameterB(CanBAddrs.KOMBI_A5, 27, 1) != 0
	
	/** Gets reserve **/
	fun get_ptt_3_2() : Boolean = CanBusNative.getECUParameterB(CanBAddrs.KOMBI_A5, 26, 1) != 0
	
	/** Gets reserve **/
	fun get_ptt_4_1() : Boolean = CanBusNative.getECUParameterB(CanBAddrs.KOMBI_A5, 25, 1) != 0
	
	/** Gets reserve **/
	fun get_ptt_4_2() : Boolean = CanBusNative.getECUParameterB(CanBAddrs.KOMBI_A5, 24, 1) != 0
	
	
}
