package com.rndash.mbheadunit.nativeCan.canB


import com.rndash.mbheadunit.nativeCan.CanBAddrs
import com.rndash.mbheadunit.nativeCan.CanBusNative



/**
 *    GENERATED BY parse_kt.py
 *    Decoder class for ECU Frame KOMBI_A6 (ID: 0x009E)
**/
object KOMBI_A6 {

	/** Identification key for pre-filtering **/
	fun get_schlue_id_ki() : Int = getParam(0, 32)

	/** (km) (Km) Mileage **/
	fun get_km_ki() : Int = getParam(32, 24)

	override fun toString(): String {
		return """
			SCHLUE_ID_KI: ${get_schlue_id_ki()}
			KM_KI: ${get_km_ki()}
		""".trimIndent()
	}


	private fun getParam(o: Int, l: Int) : Int = CanBusNative.getECUParameterB(CanBAddrs.KOMBI_A6, o, l)
}
