package com.rndash.mbheadunit.nativeCan.canB


import com.rndash.mbheadunit.nativeCan.CanBAddrs
import com.rndash.mbheadunit.nativeCan.CanBusNative



/**
 *    GENERATED BY parse_kt.py
 *    Decoder class for ECU Frame KOMBI_A7 (ID: 0x0194)
**/
object KOMBI_A7 {

	/** (%) (%) Display dimming **/
	fun get_disp_dimm() : Int = getParam(0, 8)

	/** Data radio menu activated **/
	fun get_datenf_menu_akt() : Boolean = getParam(9, 1) != 0

	/** Tailgate limiting a **/
	fun get_hd_begrenz() : Boolean = getParam(10, 1) != 0

	override fun toString(): String {
		return """
			DISP_DIMM: ${get_disp_dimm()}
			DATENF_MENU_AKT: ${get_datenf_menu_akt()}
			HD_BEGRENZ: ${get_hd_begrenz()}
		""".trimIndent()
	}


	private fun getParam(o: Int, l: Int) : Int = CanBusNative.getECUParameterB(CanBAddrs.KOMBI_A7, o, l)
}
