
package com.rndash.mbheadunit.nativeCan.canB

import com.rndash.mbheadunit.nativeCan.CanBusNative // AUTO GEN

/**
 *   Generated by db_converter.py
 *   Object for KOMBI_A3 (ID 0x00D4)
**/

object KOMBI_A3 {

    	/** Gets Current time UNIT: s **/
	fun get_a_zeit() : Int = CanBusNative.getECUParameterB(CanBAddrs.KOMBI_A3, 0, 16)
	
	/** Gets Mileage UNIT: km **/
	fun get_km() : Int = CanBusNative.getECUParameterB(CanBAddrs.KOMBI_A3, 16, 24)
	
	/** Gets Range UNIT: km (miles) **/
	fun get_rw() : Int = CanBusNative.getECUParameterB(CanBAddrs.KOMBI_A3, 40, 16)
	
	
}
