
@file:Suppress("unused", "FunctionName", "ClassName")
package com.rndash.mbheadunit.nativeCan.canB
import com.rndash.mbheadunit.CanFrame // AUTO GEN
import com.rndash.mbheadunit.nativeCan.CanBusNative // AUTO GEN

/**
 *   Generated by db_converter.py
 *   Object for MESS_TPM1 (ID 0x0607)
**/

object MESS_TPM1 {

    /** 
     *  Returns the most recent Can Frame representing the state
     *  of MESS_TPM1
    **/
    fun get_frame() : CanFrame? = CanBusNative.getBFrame(CanBAddrs.MESS_TPM1)

	/** Gets Measurement data **/
	fun get_mess_tpm1() : Int = CanBusNative.getECUParameterB(CanBAddrs.MESS_TPM1, 0, 64)
	
	/** Sets Measurement data **/
	fun set_mess_tpm1(f: CanFrame, p: Int) {
		checkFrame(f)
		CanBusNative.setFrameParameter(f, 0, 64, p)
	}
	
	/**
     * Auto generated function
     * Throws exception if user tries to set a value in a frame
     * Not designated from the correct ECU
    **/
    private fun checkFrame(f: CanFrame) {
        if (f.canID != CanBAddrs.MESS_TPM1.addr) {
            throw IllegalArgumentException("CAN ID does not match object!")
        }
    }

	override fun toString() = """
		|Frame MESS_TPM1 (0x0607):
		|	Measurement data: ${get_mess_tpm1()}
	""".trimMargin("|")
}
