
package com.rndash.mbheadunit.nativeCan.canB

import com.rndash.mbheadunit.nativeCan.CanBusNative // AUTO GEN

/**
 *   Generated by db_converter.py
 *   Object for MRM_A1 (ID 0x0006)
**/

object MRM_A1 {

    	/** Gets direction flashing left **/
	fun get_bli_li() : Boolean = CanBusNative.getECUParameterB(CanBAddrs.MRM_A1, 4, 1) != 0
	
	/** Gets right direction flashing **/
	fun get_bli_re() : Boolean = CanBusNative.getECUParameterB(CanBAddrs.MRM_A1, 3, 1) != 0
	
	/** Gets switch on high beam **/
	fun get_fl_ein() : Boolean = CanBusNative.getECUParameterB(CanBAddrs.MRM_A1, 2, 1) != 0
	
	/** Gets switch on headlight flasher **/
	fun get_lhp_ein() : Boolean = CanBusNative.getECUParameterB(CanBAddrs.MRM_A1, 1, 1) != 0
	
	/** Gets switch on the horn **/
	fun get_sgh_ein_lr() : Boolean = CanBusNative.getECUParameterB(CanBAddrs.MRM_A1, 0, 1) != 0
	
	/** Gets Wipe / wash the rear window **/
	fun get_heck_wisch_mrm() : Boolean = CanBusNative.getECUParameterB(CanBAddrs.MRM_A1, 14, 1) != 0
	
	/** Gets Intermittent wiping of the rear window **/
	fun get_heck_int_mrm() : Boolean = CanBusNative.getECUParameterB(CanBAddrs.MRM_A1, 13, 1) != 0
	
	/** Gets Tip wipe actuated **/
	fun get_tipp_wisch() : Boolean = CanBusNative.getECUParameterB(CanBAddrs.MRM_A1, 12, 1) != 0
	
	/** Gets washing actuated **/
	fun get_washing() : Boolean = CanBusNative.getECUParameterB(CanBAddrs.MRM_A1, 11, 1) != 0
	
	/** Gets LSS in position I (rain sensor operation) **/
	fun get_sch_wi_int() : Boolean = CanBusNative.getECUParameterB(CanBAddrs.MRM_A1, 10, 1) != 0
	
	/** Gets LSS in position II (level 1) **/
	fun get_sch_wi_1() : Boolean = CanBusNative.getECUParameterB(CanBAddrs.MRM_A1, 9, 1) != 0
	
	/** Gets LSS in position III (level 2) **/
	fun get_sch_wi_2() : Boolean = CanBusNative.getECUParameterB(CanBAddrs.MRM_A1, 8, 1) != 0
	
	/** Gets switch off voice control (abort) **/
	fun get_sbs_aus() : Boolean = CanBusNative.getECUParameterB(CanBAddrs.MRM_A1, 23, 1) != 0
	
	/** Gets Activate voice control (push to talk) **/
	fun get_sbs_ein() : Boolean = CanBusNative.getECUParameterB(CanBAddrs.MRM_A1, 22, 1) != 0
	
	/** Gets switch on the entry aid (if rotary knob) **/
	fun get_esh_ein_mrm() : Boolean = CanBusNative.getECUParameterB(CanBAddrs.MRM_A1, 17, 1) != 0
	
	/** Gets steering column is locked [0] (only USA) **/
	fun get_ls_st_ver() : Boolean = CanBusNative.getECUParameterB(CanBAddrs.MRM_A1, 16, 1) != 0
	
	/** Gets steering angle sign **/
	fun get_lw_vz_b() : Boolean = CanBusNative.getECUParameterB(CanBAddrs.MRM_A1, 28, 1) != 0
	
	/** Gets Steering angle sensor: not initialized **/
	fun get_lw_ini_b() : Boolean = CanBusNative.getECUParameterB(CanBAddrs.MRM_A1, 27, 1) != 0
	
	/** Gets Steering angle sensor: Code error **/
	fun get_lw_cf_b() : Boolean = CanBusNative.getECUParameterB(CanBAddrs.MRM_A1, 26, 1) != 0
	
	/** Gets Steering angle sensor: overflow **/
	fun get_lw_ov_b() : Boolean = CanBusNative.getECUParameterB(CanBAddrs.MRM_A1, 25, 1) != 0
	
	/** Gets Steering angle parity bit (even parity) **/
	fun get_lw_pa_b() : Boolean = CanBusNative.getECUParameterB(CanBAddrs.MRM_A1, 24, 1) != 0
	
	/** Gets Steering angle UNIT: ° **/
	fun get_lw_b() : Int = CanBusNative.getECUParameterB(CanBAddrs.MRM_A1, 29, 11)
	
	
}
