package com.rndash.mbheadunit.nativeCan.canB


import com.rndash.mbheadunit.nativeCan.CanBAddrs
import com.rndash.mbheadunit.nativeCan.CanBusNative



/**
 *    GENERATED BY parse_kt.py
 *    Decoder class for ECU Frame MRM_A3 (ID: 0x0296)
**/
object MRM_A3 {

	/** Steering column to the rear (toward the driver) **/
	fun get_ls_zur_mrm() : Boolean = getParam(0, 1) != 0

	/** Steering column to the front **/
	fun get_ls_vor_mrm() : Boolean = getParam(1, 1) != 0

	/** Steering column downward **/
	fun get_ls_ab_mrm() : Boolean = getParam(2, 1) != 0

	/** Steering column according to above **/
	fun get_ls_auf_mrm() : Boolean = getParam(3, 1) != 0

	/** Steering column adjustment lever is turned down **/
	fun get_lsvh_un() : Boolean = getParam(4, 1) != 0

	/** Steering column adjustment lever rotated upward **/
	fun get_lsvh_ob() : Boolean = getParam(5, 1) != 0

	override fun toString(): String {
		return """
			LS_ZUR_MRM: ${get_ls_zur_mrm()}
			LS_VOR_MRM: ${get_ls_vor_mrm()}
			LS_AB_MRM: ${get_ls_ab_mrm()}
			LS_AUF_MRM: ${get_ls_auf_mrm()}
			LSVH_UN: ${get_lsvh_un()}
			LSVH_OB: ${get_lsvh_ob()}
		""".trimIndent()
	}


	private fun getParam(o: Int, l: Int) : Int = CanBusNative.getECUParameterB(CanBAddrs.MRM_A3, o, l)
}
