
package com.rndash.mbheadunit.nativeCan.canB

import com.rndash.mbheadunit.nativeCan.CanBusNative // AUTO GEN

/**
 *   Generated by db_converter.py
 *   Object for MSS_A2 (ID 0x01AE)
**/

object MSS_A2 {

    	/** Gets Electronics on the MSS defective **/
	fun get_mss_ee_def() : Boolean = CanBusNative.getECUParameterB(CanBAddrs.MSS_A2, 7, 1) != 0
	
	/** Gets Emergency alarm system defective **/
	fun get_notalm_def() : Boolean = CanBusNative.getECUParameterB(CanBAddrs.MSS_A2, 6, 1) != 0
	
	/** Gets Silent alarm triggered **/
	fun get_mss_alm() : Boolean = CanBusNative.getECUParameterB(CanBAddrs.MSS_A2, 5, 1) != 0
	
	/** Gets MSS detects undervoltage **/
	fun get_mss_uspg() : Boolean = CanBusNative.getECUParameterB(CanBAddrs.MSS_A2, 4, 1) != 0
	
	/** Gets roof sign defective (short circuit) **/
	fun get_dz_def() : Boolean = CanBusNative.getECUParameterB(CanBAddrs.MSS_A2, 3, 1) != 0
	
	/** Gets check roof sign (interruption) **/
	fun get_dz_prf() : Boolean = CanBusNative.getECUParameterB(CanBAddrs.MSS_A2, 2, 1) != 0
	
	/** Gets Roof sign lamp defect **/
	fun get_dz_la_def() : Boolean = CanBusNative.getECUParameterB(CanBAddrs.MSS_A2, 1, 1) != 0
	
	/** Gets Roof sign control lamp on **/
	fun get_dz_kl() : Boolean = CanBusNative.getECUParameterB(CanBAddrs.MSS_A2, 0, 1) != 0
	
	/** Gets fog cartridge empty **/
	fun get_np_leer() : Boolean = CanBusNative.getECUParameterB(CanBAddrs.MSS_A2, 15, 1) != 0
	
	/** Gets Fog system activated **/
	fun get_nebel_akt() : Boolean = CanBusNative.getECUParameterB(CanBAddrs.MSS_A2, 14, 1) != 0
	
	/** Gets Fog system out of order **/
	fun get_nebel_aus() : Boolean = CanBusNative.getECUParameterB(CanBAddrs.MSS_A2, 13, 1) != 0
	
	/** Gets fresh air bottle empty **/
	fun get_o2_leer() : Boolean = CanBusNative.getECUParameterB(CanBAddrs.MSS_A2, 12, 1) != 0
	
	/** Gets fresh air system activated **/
	fun get_o2_akt() : Boolean = CanBusNative.getECUParameterB(CanBAddrs.MSS_A2, 11, 1) != 0
	
	/** Gets fresh air system out of order **/
	fun get_o2_aus() : Boolean = CanBusNative.getECUParameterB(CanBAddrs.MSS_A2, 10, 1) != 0
	
	/** Gets control buzzer in combi **/
	fun get_mss_summer() : Boolean = CanBusNative.getECUParameterB(CanBAddrs.MSS_A2, 9, 1) != 0
	
	/** Gets radio status **/
	fun get_fnk_stat() : Boolean = CanBusNative.getECUParameterB(CanBAddrs.MSS_A2, 8, 1) != 0
	
	/** Gets MSS detects undervoltage when the motor is running **/
	fun get_mss_uspg_mo() : Boolean = CanBusNative.getECUParameterB(CanBAddrs.MSS_A2, 21, 1) != 0
	
	
}
