package com.rndash.mbheadunit.nativeCan.canB


import com.rndash.mbheadunit.nativeCan.CanBAddrs
import com.rndash.mbheadunit.nativeCan.CanBusNative



/**
 *    GENERATED BY parse_kt.py
 *    Decoder class for ECU Frame MSS_A4 (ID: 0x0248)
**/
object MSS_A4 {

	/** Close rear right **/
	fun get_fhr_alarm() : Boolean = getParam(0, 1) != 0

	/** Close rear left **/
	fun get_fhl_alarm() : Boolean = getParam(1, 1) != 0

	/** Close window front right **/
	fun get_fvr_alarm() : Boolean = getParam(2, 1) != 0

	/** Close front left **/
	fun get_fvl_alarm() : Boolean = getParam(3, 1) != 0

	/** close SHD **/
	fun get_shd_alarm() : Boolean = getParam(4, 1) != 0

	/** Line Alert operation **/
	fun get_ri_alarm() : Boolean = getParam(5, 1) != 0

	/** SHD / window Run **/
	fun get_mod_alarm() : Boolean = getParam(6, 1) != 0

	override fun toString(): String {
		return """
			FHR_ALARM: ${get_fhr_alarm()}
			FHL_ALARM: ${get_fhl_alarm()}
			FVR_ALARM: ${get_fvr_alarm()}
			FVL_ALARM: ${get_fvl_alarm()}
			SHD_ALARM: ${get_shd_alarm()}
			RI_ALARM: ${get_ri_alarm()}
			MOD_ALARM: ${get_mod_alarm()}
		""".trimIndent()
	}


	private fun getParam(o: Int, l: Int) : Int = CanBusNative.getECUParameterB(CanBAddrs.MSS_A4, o, l)
}
