package com.rndash.mbheadunit.nativeCan.canB


import com.rndash.mbheadunit.nativeCan.CanBAddrs
import com.rndash.mbheadunit.nativeCan.CanBusNative



/**
 *    GENERATED BY parse_kt.py
 *    Decoder class for ECU Frame MSS_A2 (ID: 0x01AE)
**/
object MSS_A2 {

	/** Roof sign warning light a **/
	fun get_dz_kl() : Boolean = getParam(0, 1) != 0

	/** Roof sign lamp defect **/
	fun get_dz_la_def() : Boolean = getParam(1, 1) != 0

	/** Check roof sign (interruption) **/
	fun get_dz_prf() : Boolean = getParam(2, 1) != 0

	/** Roof sign defective (short circuit) **/
	fun get_dz_def() : Boolean = getParam(3, 1) != 0

	/** MSS detects undervoltage **/
	fun get_mss_uspg() : Boolean = getParam(4, 1) != 0

	/** Silent alarm triggered **/
	fun get_mss_alm() : Boolean = getParam(5, 1) != 0

	/** Emergency alarm system is defective **/
	fun get_notalm_def() : Boolean = getParam(6, 1) != 0

	/** Electrical on MSS defective **/
	fun get_mss_ee_def() : Boolean = getParam(7, 1) != 0

	/** Radio Status **/
	fun get_fnk_stat() : Boolean = getParam(8, 1) != 0

	/** Summer drive in combination **/
	fun get_mss_summer() : Boolean = getParam(9, 1) != 0

	/** Fresh air system out of service **/
	fun get_o2_aus() : Boolean = getParam(10, 1) != 0

	/** Fresh air system activated **/
	fun get_o2_akt() : Boolean = getParam(11, 1) != 0

	/** Fresh air bottle is empty **/
	fun get_o2_leer() : Boolean = getParam(12, 1) != 0

	/** Fog system out of service **/
	fun get_nebel_aus() : Boolean = getParam(13, 1) != 0

	/** Mist system activated **/
	fun get_nebel_akt() : Boolean = getParam(14, 1) != 0

	/** Fog cartridge empty **/
	fun get_np_leer() : Boolean = getParam(15, 1) != 0

	/** MSS detects under-voltage when the engine is running **/
	fun get_mss_uspg_mo() : Boolean = getParam(21, 1) != 0

	override fun toString(): String {
		return """
			DZ_KL: ${get_dz_kl()}
			DZ_LA_DEF: ${get_dz_la_def()}
			DZ_PRF: ${get_dz_prf()}
			DZ_DEF: ${get_dz_def()}
			MSS_USPG: ${get_mss_uspg()}
			MSS_ALM: ${get_mss_alm()}
			NOTALM_DEF: ${get_notalm_def()}
			MSS_EE_DEF: ${get_mss_ee_def()}
			FNK_STAT: ${get_fnk_stat()}
			MSS_SUMMER: ${get_mss_summer()}
			O2_AUS: ${get_o2_aus()}
			O2_AKT: ${get_o2_akt()}
			O2_LEER: ${get_o2_leer()}
			NEBEL_AUS: ${get_nebel_aus()}
			NEBEL_AKT: ${get_nebel_akt()}
			NP_LEER: ${get_np_leer()}
			MSS_USPG_MO: ${get_mss_uspg_mo()}
		""".trimIndent()
	}


	private fun getParam(o: Int, l: Int) : Int = CanBusNative.getECUParameterB(CanBAddrs.MSS_A2, o, l)
}
