
package com.rndash.mbheadunit.nativeCan.canB

import com.rndash.mbheadunit.nativeCan.CanBusNative // AUTO GEN

/**
 *   Generated by db_converter.py
 *   Object for MSSK_A2 (ID 0x0208)
**/

object MSSK_A2 {

    	/** Gets passenger seat **/
	fun get_sbf_vor_k() : Boolean = CanBusNative.getECUParameterB(CanBAddrs.MSSK_A2, 7, 1) != 0
	
	/** Gets passenger seat **/
	fun get_sbf_zur_k() : Boolean = CanBusNative.getECUParameterB(CanBAddrs.MSSK_A2, 6, 1) != 0
	
	/** Gets passenger seat **/
	fun get_sbf_k_tgl() : Boolean = CanBusNative.getECUParameterB(CanBAddrs.MSSK_A2, 0, 1) != 0
	
	
}
