
package com.rndash.mbheadunit.nativeCan.canB

import com.rndash.mbheadunit.nativeCan.CanBusNative // AUTO GEN

/**
 *   Generated by db_converter.py
 *   Object for OBF_A1 (ID 0x002C)
**/

object OBF_A1 {

    	/** Gets ESP on / off actuated **/
	fun get_esp_bet() : ESP_BET = when(CanBusNative.getECUParameterB(CanBAddrs.OBF_A1, 6, 2)) {
		 0 -> ESP_BET.NBET
		 1 -> ESP_BET.EIN_NDEF
		 2 -> ESP_BET.AUS_BET
		 3 -> ESP_BET.SNV
		 else -> throw Exception("Invalid raw value for ESP_BET")
	}
	
	/** Gets Rear head restraints raised / lowered actuated **/
	fun get_fks_bet() : Boolean = CanBusNative.getECUParameterB(CanBAddrs.OBF_A1, 4, 1) != 0
	
	/** Gets Rear blind button pressed **/
	fun get_hr_bet() : Boolean = CanBusNative.getECUParameterB(CanBAddrs.OBF_A1, 2, 1) != 0
	
	/** Gets unlock ZV (internal switch activated) **/
	fun get_zv_entri_is() : Boolean = CanBusNative.getECUParameterB(CanBAddrs.OBF_A1, 1, 1) != 0
	
	/** Gets lock ZV (internal switch actuated) **/
	fun get_zv_verri_is() : Boolean = CanBusNative.getECUParameterB(CanBAddrs.OBF_A1, 0, 1) != 0
	
	/** Gets EDW glove box contact triggered **/
	fun get_edw_hand_auf() : Boolean = CanBusNative.getECUParameterB(CanBAddrs.OBF_A1, 15, 1) != 0
	
	/** Gets Deselect EDW interior protection **/
	fun get_edw_irs_abw() : Boolean = CanBusNative.getECUParameterB(CanBAddrs.OBF_A1, 14, 1) != 0
	
	/** Gets EDW deselect towing protection **/
	fun get_edw_as_abw() : Boolean = CanBusNative.getECUParameterB(CanBAddrs.OBF_A1, 13, 1) != 0
	
	/** Gets Hazard warning lights on **/
	fun get_wbl_ein() : Boolean = CanBusNative.getECUParameterB(CanBAddrs.OBF_A1, 10, 1) != 0
	
	/** Gets Parktronic button pressed **/
	fun get_pts_bet() : Boolean = CanBusNative.getECUParameterB(CanBAddrs.OBF_A1, 16, 1) != 0
	
	
}
