
@file:Suppress("unused", "FunctionName", "ClassName")
package com.rndash.mbheadunit.nativeCan.canB
import com.rndash.mbheadunit.CanFrame // AUTO GEN
import com.rndash.mbheadunit.nativeCan.CanBusNative // AUTO GEN

/**
 *   Generated by db_converter.py
 *   Object for PTS_A1 (ID 0x02B0)
**/

object PTS_A1 {

    /** 
     *  Returns the most recent Can Frame representing the state
     *  of PTS_A1
    **/
    fun get_frame() : CanFrame? = CanBusNative.getBFrame(CanBAddrs.PTS_A1)

	/** Gets PTS is completely switched off **/
	fun get_pts_st_aus() : Boolean = CanBusNative.getECUParameterB(CanBAddrs.PTS_A1, 0, 1) != 0
	
	/** Sets PTS is completely switched off **/
	fun set_pts_st_aus(f: CanFrame, p: Boolean) : CanFrame? {
		checkFrame(f)
		return CanBusNative.setFrameParameter(f, 0, 1, if(p) 1 else 0)
	}
	
	/**
     * Auto generated function
     * Throws exception if user tries to set a value in a frame
     * Not designated from the correct ECU
    **/
    private fun checkFrame(f: CanFrame) {
        if (f.canID != CanBAddrs.PTS_A1.addr) {
            throw IllegalArgumentException("CAN ID does not match object!")
        }
    }

	override fun toString() = """
		|PTS is completely switched off: ${get_pts_st_aus()}
	""".trimMargin("|")
}
