package com.rndash.mbheadunit.nativeCan.canB


import com.rndash.mbheadunit.nativeCan.CanBAddrs
import com.rndash.mbheadunit.nativeCan.CanBusNative



/**
 *    GENERATED BY parse_kt.py
 *    Decoder class for ECU Frame PTS_A1 (ID: 0x02B0)
**/
object PTS_A1 {

	/** PTS ist komplett ausgeschaltet **/
	fun get_pts_st_aus() : Boolean = getParam(0, 1) != 0

	override fun toString(): String {
		return """
			PTS_ST_AUS: ${get_pts_st_aus()}
		""".trimIndent()
	}


	private fun getParam(o: Int, l: Int) : Int = CanBusNative.getECUParameterB(CanBAddrs.PTS_A1, o, l)
}
