
package com.rndash.mbheadunit.nativeCan.canB

import com.rndash.mbheadunit.nativeCan.CanBusNative // AUTO GEN

/**
 *   Generated by db_converter.py
 *   Object for PTS_A1 (ID 0x02B0)
**/

object PTS_A1 {

    	/** Gets PTS is completely switched off **/
	fun get_pts_st_aus() : Boolean = CanBusNative.getECUParameterB(CanBAddrs.PTS_A1, 0, 1) != 0
	
	
}
