package com.rndash.mbheadunit.nativeCan.canB


import com.rndash.mbheadunit.nativeCan.CanBAddrs
import com.rndash.mbheadunit.nativeCan.CanBusNative



/**
 *    GENERATED BY parse_kt.py
 *    Decoder class for ECU Frame SAM_V_A2 (ID: 0x0017)
**/
object SAM_V_A2 {

	/** (°C) (° C) Outside air temperature **/
	fun get_t_aussen_b() : Int = getParam(0, 8)

	/** (bar) (Bar) pressure refrigerant R134a **/
	fun get_p_kaelte() : Int = getParam(8, 16)

	/** (°C) (° C) temperature refrigerant R134a **/
	fun get_t_kaelte() : Int = getParam(24, 16)

	/** (mA) (MA) current compressor main control valve **/
	fun get_i_komp() : Int = getParam(40, 8)

	override fun toString(): String {
		return """
			T_AUSSEN_B: ${get_t_aussen_b()}
			P_KAELTE: ${get_p_kaelte()}
			T_KAELTE: ${get_t_kaelte()}
			I_KOMP: ${get_i_komp()}
		""".trimIndent()
	}


	private fun getParam(o: Int, l: Int) : Int = CanBusNative.getECUParameterB(CanBAddrs.SAM_V_A2, o, l)
}
