
package com.rndash.mbheadunit.nativeCan.canB

import com.rndash.mbheadunit.nativeCan.CanBusNative // AUTO GEN

/**
 *   Generated by db_converter.py
 *   Object for SAM_H_A5 (ID 0x0230)
**/

object SAM_H_A5 {

    	/** Gets switch on tail light **/
	fun get_sl_ein_edw() : Boolean = CanBusNative.getECUParameterB(CanBAddrs.SAM_H_A5, 2, 1) != 0
	
	/** Gets switch on low beam **/
	fun get_abl_ein_edw() : Boolean = CanBusNative.getECUParameterB(CanBAddrs.SAM_H_A5, 1, 1) != 0
	
	/** Gets switch on fog lights **/
	fun get_nsw_ein_edw() : Boolean = CanBusNative.getECUParameterB(CanBAddrs.SAM_H_A5, 0, 1) != 0
	
	/** Gets Duration light-bright phase UNIT: ms **/
	fun get_hell_edw() : Int = CanBusNative.getECUParameterB(CanBAddrs.SAM_H_A5, 8, 8)
	
	
}
