package com.rndash.mbheadunit.nativeCan.canB


import com.rndash.mbheadunit.nativeCan.CanBAddrs
import com.rndash.mbheadunit.nativeCan.CanBusNative



/**
 *    GENERATED BY parse_kt.py
 *    Decoder class for ECU Frame SAM_H_A1 (ID: 0x0004)
**/
object SAM_H_A1 {

	/** Panic alarm is active **/
	fun get_pnk_akt() : Boolean = getParam(0, 1) != 0

	/** Terminal 54 Hardware enabled **/
	fun get_kl54_rm() : Boolean = getParam(1, 1) != 0

	/** down tailgate Contact **/
	fun get_hdk_bet() : Boolean = getParam(2, 1) != 0

	/** Boot lid is on **/
	fun get_hd_auf() : Boolean = getParam(3, 1) != 0

	/** Rear door is right **/
	fun get_thr_auf() : Boolean = getParam(4, 1) != 0

	/** Door rear left on **/
	fun get_thl_auf() : Boolean = getParam(5, 1) != 0

	/** Front door is right **/
	fun get_tvr_auf() : Boolean = getParam(6, 1) != 0

	/** Door front left **/
	fun get_tvl_auf() : Boolean = getParam(7, 1) != 0

	/** Bonnet is on **/
	fun get_mot_auf() : Boolean = getParam(8, 1) != 0

	/** Height adjuster passenger unlocked **/
	fun get_hvst_bf_ent() : Boolean = getParam(9, 1) != 0

	/** Height adjuster driver unlocks **/
	fun get_hvst_f_ent() : Boolean = getParam(10, 1) != 0

	/** Heizb. Rear window is switched off due to undervoltage. **/
	fun get_hhs_st_uspg() : Boolean = getParam(11, 1) != 0

	/** Heated rear window is on **/
	fun get_hhs_st_ein() : Boolean = getParam(12, 1) != 0

	/** Rear lock is secured **/
	fun get_hschl_st_sich() : Boolean = getParam(13, 1) != 0

	/** Rear lock in 90 ° position, **/
	fun get_hschl_zu() : Boolean = getParam(14, 1) != 0

	/** Rear lid lock pawl actuated **/
	fun get_hd_sk_sam_h() : Boolean = getParam(15, 1) != 0

	/** Switch EDW interior light **/
	fun get_edw_il_ein() : Boolean = getParam(16, 1) != 0

	/** EDW sharpened **/
	fun get_edw_akt() : Boolean = getParam(17, 1) != 0

	/** Enable EDW interior protection **/
	fun get_edw_irs_akt() : Boolean = getParam(18, 1) != 0

	/** Enable EDW-trailer monitoring **/
	fun get_edw_aag_akt() : Boolean = getParam(19, 1) != 0

	/** EDW alarm triggered **/
	fun get_edw_alarm() : Boolean = getParam(20, 1) != 0

	/** Plate light left broken **/
	fun get_kzl_def_l() : Boolean = getParam(24, 1) != 0

	/** Reversing light Left defective **/
	fun get_rfl_def_l() : Boolean = getParam(25, 1) != 0

	/** Left brake light is defective **/
	fun get_bl_def_l() : Boolean = getParam(26, 1) != 0

	/** Bottom left defective **/
	fun get_sl_def_l() : Boolean = getParam(27, 1) != 0

	/** Indicator rear left defective **/
	fun get_bli_def_hl() : Boolean = getParam(28, 1) != 0

	/** Rear fog light broken **/
	fun get_nsl_def() : Boolean = getParam(29, 1) != 0

	/** 3rd brake light is defective **/
	fun get_bl3_def() : Boolean = getParam(30, 1) != 0

	/** Terminal 54 errors **/
	fun get_kl_54_def() : Boolean = getParam(31, 1) != 0

	/** Plate light right defective **/
	fun get_kzl_def_r() : Boolean = getParam(32, 1) != 0

	/** Reversing light Right defective **/
	fun get_rfl_def_r() : Boolean = getParam(33, 1) != 0

	/** Stoplight right defective **/
	fun get_bl_def_r() : Boolean = getParam(34, 1) != 0

	/** Bottom right defective **/
	fun get_sl_def_r() : Boolean = getParam(35, 1) != 0

	/** Rear right turn signal defective **/
	fun get_bli_def_hr() : Boolean = getParam(36, 1) != 0

	/** Side marker defective rear right **/
	fun get_sm_def_hr() : Boolean = getParam(38, 1) != 0

	/** Sidemarker rear left defective **/
	fun get_sm_def_hl() : Boolean = getParam(39, 1) != 0

	/** Replacement light rear fog lamp (s) active **/
	fun get_nsl_ers() : Boolean = getParam(40, 1) != 0

	/** Replacement light tail light, rear right active **/
	fun get_sl_ers_hr() : Boolean = getParam(42, 1) != 0

	/** Replacement light Rear right turn signal active **/
	fun get_bli_ers_hr() : Boolean = getParam(43, 1) != 0

	/** Replacement light rear lights, left active **/
	fun get_sl_ers_hl() : Boolean = getParam(46, 1) != 0

	/** Replacement light Indicator rear left active **/
	fun get_bli_ers_hl() : Boolean = getParam(47, 1) != 0

	/** Rear wiper interval operation **/
	fun get_hw_int_akt() : Boolean = getParam(48, 1) != 0

	/** Belt KL on (for G463) **/
	fun get_gurt_kl_hw() : Boolean = getParam(49, 1) != 0

	/** SRS warning light (for G463) **/
	fun get_srs_kl_hw() : Boolean = getParam(50, 1) != 0

	/** Switch HFS search lights **/
	fun get_hfs_sb_ein() : Boolean = getParam(51, 1) != 0

	/** Button Heckd. operated close **/
	fun get_hd_schliess_sam_h() : Boolean = getParam(52, 1) != 0

	/** Button Heckd. Close & Secure operated **/
	fun get_hd_sich_sam_h() : Boolean = getParam(53, 1) != 0

	override fun toString(): String {
		return """
			PNK_AKT: ${get_pnk_akt()}
			KL54_RM: ${get_kl54_rm()}
			HDK_BET: ${get_hdk_bet()}
			HD_AUF: ${get_hd_auf()}
			THR_AUF: ${get_thr_auf()}
			THL_AUF: ${get_thl_auf()}
			TVR_AUF: ${get_tvr_auf()}
			TVL_AUF: ${get_tvl_auf()}
			MOT_AUF: ${get_mot_auf()}
			HVST_BF_ENT: ${get_hvst_bf_ent()}
			HVST_F_ENT: ${get_hvst_f_ent()}
			HHS_ST_USPG: ${get_hhs_st_uspg()}
			HHS_ST_EIN: ${get_hhs_st_ein()}
			HSCHL_ST_SICH: ${get_hschl_st_sich()}
			HSCHL_ZU: ${get_hschl_zu()}
			HD_SK_SAM_H: ${get_hd_sk_sam_h()}
			EDW_IL_EIN: ${get_edw_il_ein()}
			EDW_AKT: ${get_edw_akt()}
			EDW_IRS_AKT: ${get_edw_irs_akt()}
			EDW_AAG_AKT: ${get_edw_aag_akt()}
			EDW_ALARM: ${get_edw_alarm()}
			KZL_DEF_L: ${get_kzl_def_l()}
			RFL_DEF_L: ${get_rfl_def_l()}
			BL_DEF_L: ${get_bl_def_l()}
			SL_DEF_L: ${get_sl_def_l()}
			BLI_DEF_HL: ${get_bli_def_hl()}
			NSL_DEF: ${get_nsl_def()}
			BL3_DEF: ${get_bl3_def()}
			KL_54_DEF: ${get_kl_54_def()}
			KZL_DEF_R: ${get_kzl_def_r()}
			RFL_DEF_R: ${get_rfl_def_r()}
			BL_DEF_R: ${get_bl_def_r()}
			SL_DEF_R: ${get_sl_def_r()}
			BLI_DEF_HR: ${get_bli_def_hr()}
			SM_DEF_HR: ${get_sm_def_hr()}
			SM_DEF_HL: ${get_sm_def_hl()}
			NSL_ERS: ${get_nsl_ers()}
			SL_ERS_HR: ${get_sl_ers_hr()}
			BLI_ERS_HR: ${get_bli_ers_hr()}
			SL_ERS_HL: ${get_sl_ers_hl()}
			BLI_ERS_HL: ${get_bli_ers_hl()}
			HW_INT_AKT: ${get_hw_int_akt()}
			GURT_KL_HW: ${get_gurt_kl_hw()}
			SRS_KL_HW: ${get_srs_kl_hw()}
			HFS_SB_EIN: ${get_hfs_sb_ein()}
			HD_SCHLIESS_SAM_H: ${get_hd_schliess_sam_h()}
			HD_SICH_SAM_H: ${get_hd_sich_sam_h()}
		""".trimIndent()
	}


	private fun getParam(o: Int, l: Int) : Int = CanBusNative.getECUParameterB(CanBAddrs.SAM_H_A1, o, l)
}
