package com.rndash.mbheadunit.nativeCan.canB


import com.rndash.mbheadunit.nativeCan.CanBAddrs
import com.rndash.mbheadunit.nativeCan.CanBusNative



/**
 *    GENERATED BY parse_kt.py
 *    Decoder class for ECU Frame SAM_V_A3 (ID: 0x0070)
**/
object SAM_V_A3 {

	/** Parity (even) of bit 0 to 6 **/
	fun get_parity_sam_v() : Boolean = getParam(0, 1) != 0

	/** Rain sensor configuration **/
	fun get_konfig_rs() : Int = getParam(2, 3)

	/** washing actuated **/
	fun get_kl_86_ein() : Boolean = getParam(5, 1) != 0

	/** Wiper park position outside **/
	fun get_kl_31b_ein() : Boolean = getParam(6, 1) != 0

	/** Rain sensor activated **/
	fun get_rs_akt() : Boolean = getParam(7, 1) != 0

	/** a byte code **/
	fun get_byte_kenn() : Int = getParam(8, 2)

	/** Diagnosis rain sensor **/
	fun get_diag_rs() : Boolean = getParam(10, 1) != 0

	/** Rain sensor operation is not possible **/
	fun get_rs_nm() : Boolean = getParam(11, 1) != 0

	/** SAM_V initialization **/
	fun get_sam_v_init() : Boolean = getParam(12, 1) != 0

	/** washing actuated **/
	fun get_kl_86_rs() : Boolean = getParam(13, 1) != 0

	/** Wiper outside parking position **/
	fun get_kl_31b_rs() : Boolean = getParam(14, 1) != 0

	/** Rain sensor on / off (position interval) **/
	fun get_rs_int() : Boolean = getParam(15, 1) != 0

	override fun toString(): String {
		return """
			PARITY_SAM_V: ${get_parity_sam_v()}
			KONFIG_RS: ${get_konfig_rs()}
			KL_86_EIN: ${get_kl_86_ein()}
			KL_31B_EIN: ${get_kl_31b_ein()}
			RS_AKT: ${get_rs_akt()}
			BYTE_KENN: ${get_byte_kenn()}
			DIAG_RS: ${get_diag_rs()}
			RS_NM: ${get_rs_nm()}
			SAM_V_INIT: ${get_sam_v_init()}
			KL_86_RS: ${get_kl_86_rs()}
			KL_31B_RS: ${get_kl_31b_rs()}
			RS_INT: ${get_rs_int()}
		""".trimIndent()
	}


	private fun getParam(o: Int, l: Int) : Int = CanBusNative.getECUParameterB(CanBAddrs.SAM_V_A3, o, l)
}
