package com.rndash.mbheadunit.nativeCan.canB


import com.rndash.mbheadunit.nativeCan.CanBAddrs
import com.rndash.mbheadunit.nativeCan.CanBusNative



/**
 *    GENERATED BY parse_kt.py
 *    Decoder class for ECU Frame SAM_H_A3 (ID: 0x000E)
**/
object SAM_H_A3 {

	/** Turn Right indicator **/
	fun get_bli_re_ein() : Boolean = getParam(0, 1) != 0

	/** Turn left turn signal **/
	fun get_bli_li_ein() : Boolean = getParam(1, 1) != 0

	/** Hazard lights active **/
	fun get_warn_akt() : Boolean = getParam(2, 1) != 0

	/** (ms) (Ms) Flashing-light light phase **/
	fun get_hell_blink() : Int = getParam(8, 8)

	override fun toString(): String {
		return """
			BLI_RE_EIN: ${get_bli_re_ein()}
			BLI_LI_EIN: ${get_bli_li_ein()}
			WARN_AKT: ${get_warn_akt()}
			HELL_BLINK: ${get_hell_blink()}
		""".trimIndent()
	}


	private fun getParam(o: Int, l: Int) : Int = CanBusNative.getECUParameterB(CanBAddrs.SAM_H_A3, o, l)
}
