
@file:Suppress("unused", "FunctionName")
package com.rndash.mbheadunit.nativeCan.canB
import com.rndash.mbheadunit.CanFrame // AUTO GEN
import com.rndash.mbheadunit.nativeCan.CanBusNative // AUTO GEN

/**
 *   Generated by db_converter.py
 *   Object for SAM_H_A3 (ID 0x000E)
**/

object SAM_H_A3 {

    	/** Gets Hazard warning lights active **/
	fun get_warn_akt() : Boolean = CanBusNative.getECUParameterB(CanBAddrs.SAM_H_A3, 2, 1) != 0
	
	/** Sets Hazard warning lights active **/
	fun set_warn_akt(f: CanFrame, p: Boolean) = CanBusNative.setFrameParameter(f, 2, 1, if(p) 1 else 0)
	
	/** Gets Switch on the left turn signal **/
	fun get_bli_li_ein() : Boolean = CanBusNative.getECUParameterB(CanBAddrs.SAM_H_A3, 1, 1) != 0
	
	/** Sets Switch on the left turn signal **/
	fun set_bli_li_ein(f: CanFrame, p: Boolean) = CanBusNative.setFrameParameter(f, 1, 1, if(p) 1 else 0)
	
	/** Gets Switch on the right turn signal **/
	fun get_bli_re_ein() : Boolean = CanBusNative.getECUParameterB(CanBAddrs.SAM_H_A3, 0, 1) != 0
	
	/** Sets Switch on the right turn signal **/
	fun set_bli_re_ein(f: CanFrame, p: Boolean) = CanBusNative.setFrameParameter(f, 0, 1, if(p) 1 else 0)
	
	/** Gets Flashing-light-bright phase UNIT: ms **/
	fun get_hell_blink() : Int = CanBusNative.getECUParameterB(CanBAddrs.SAM_H_A3, 8, 8)
	
	/** Sets Flashing-light-bright phase UNIT: ms **/
	fun set_hell_blink(f: CanFrame, p: Int) = CanBusNative.setFrameParameter(f, 8, 8, p)
	
	
}
