
package com.rndash.mbheadunit.nativeCan.canB

import com.rndash.mbheadunit.nativeCan.CanBusNative // AUTO GEN

/**
 *   Generated by db_converter.py
 *   Object for SAM_H_A4 (ID 0x0041)
**/

object SAM_H_A4 {

    	/** Gets ZV emergency opening **/
	fun get_zv_notoeff() : Boolean = CanBusNative.getECUParameterB(CanBAddrs.SAM_H_A4, 7, 1) != 0
	
	/** Gets lock follower 1 (unlock) **/
	fun get_sn1_sam_h() : Boolean = CanBusNative.getECUParameterB(CanBAddrs.SAM_H_A4, 1, 1) != 0
	
	
}
