package com.rndash.mbheadunit.nativeCan.canB


import com.rndash.mbheadunit.nativeCan.CanBAddrs
import com.rndash.mbheadunit.nativeCan.CanBusNative



/**
 *    GENERATED BY parse_kt.py
 *    Decoder class for ECU Frame SB_A1 (ID: 0x01B6)
**/
object SB_A1 {

	/** Lehne Beifahrersitz entriegelt **/
	fun get_le_b_ent() : Boolean = getParam(4, 1) != 0

	override fun toString(): String {
		return """
			LE_B_ENT: ${get_le_b_ent()}
		""".trimIndent()
	}


	private fun getParam(o: Int, l: Int) : Int = CanBusNative.getECUParameterB(CanBAddrs.SB_A1, o, l)
}
