package com.rndash.mbheadunit.nativeCan.canB


import com.rndash.mbheadunit.nativeCan.CanBAddrs
import com.rndash.mbheadunit.nativeCan.CanBusNative



/**
 *    GENERATED BY parse_kt.py
 *    Decoder class for ECU Frame SF_A2 (ID: 0x02D0)
**/
object SF_A2 {

	/** Entry / exit is approaching a position actively **/
	fun get_esh_akt() : Boolean = getParam(0, 1) != 0

	/** Driving position to approach active **/
	fun get_auto_akt() : Boolean = getParam(1, 1) != 0

	/** save manually set position **/
	fun get_mf_man_sp() : Boolean = getParam(2, 1) != 0

	/** perform positioning mirror **/
	fun get_esh_auto_rest() : Boolean = getParam(5, 1) != 0

	override fun toString(): String {
		return """
			ESH_AKT: ${get_esh_akt()}
			AUTO_AKT: ${get_auto_akt()}
			MF_MAN_SP: ${get_mf_man_sp()}
			ESH_AUTO_REST: ${get_esh_auto_rest()}
		""".trimIndent()
	}


	private fun getParam(o: Int, l: Int) : Int = CanBusNative.getECUParameterB(CanBAddrs.SF_A2, o, l)
}
