package com.rndash.mbheadunit.nativeCan.canB


import com.rndash.mbheadunit.nativeCan.CanBAddrs
import com.rndash.mbheadunit.nativeCan.CanBusNative



/**
 *    GENERATED BY parse_kt.py
 *    Decoder class for ECU Frame SF_A1 (ID: 0x01AC)
**/
object SF_A1 {

	/** save manually set position (redundant) **/
	fun get_mf_man_sp1() : Boolean = getParam(0, 1) != 0

	/** Back seat driver unlocked **/
	fun get_le_f_ent() : Boolean = getParam(4, 1) != 0

	/** (Abschnitte) (Sections) driver seat position **/
	fun get_sf_pos() : Int = getParam(8, 8)

	/** (Abschnitte) (Sections) default position for driver's seat at I / O help **/
	fun get_sf_ea_def() : Int = getParam(16, 8)

	override fun toString(): String {
		return """
			MF_MAN_SP1: ${get_mf_man_sp1()}
			LE_F_ENT: ${get_le_f_ent()}
			SF_POS: ${get_sf_pos()}
			SF_EA_DEF: ${get_sf_ea_def()}
		""".trimIndent()
	}


	private fun getParam(o: Int, l: Int) : Int = CanBusNative.getECUParameterB(CanBAddrs.SF_A1, o, l)
}
