package com.rndash.mbheadunit.nativeCan.canB


import com.rndash.mbheadunit.nativeCan.CanBAddrs
import com.rndash.mbheadunit.nativeCan.CanBusNative



/**
 *    GENERATED BY parse_kt.py
 *    Decoder class for ECU Frame TELEAID_POS3 (ID: 0x03E7)
**/
object TELEAID_POS3 {

	/** (years) (Years) GPS dateyear **/
	fun get_gps_date_year() : Int = getParam(0, 16)

	/** (months) (Months) GPS datemonth **/
	fun get_gps_date_month() : Int = getParam(16, 8)

	/** (days) (Days) GPS date day **/
	fun get_gps_date_day() : Int = getParam(24, 8)

	/** (h) (H) GPS UTC hour **/
	fun get_gps_utc_hour() : Int = getParam(32, 8)

	/** (min) (Min) GPS UTC minute **/
	fun get_gps_utc_minute() : Int = getParam(40, 8)

	/** (s) (S) GPS UTC second **/
	fun get_gps_utc_second() : Int = getParam(48, 16)

	override fun toString(): String {
		return """
			GPS_DATE_YEAR: ${get_gps_date_year()}
			GPS_DATE_MONTH: ${get_gps_date_month()}
			GPS_DATE_DAY: ${get_gps_date_day()}
			GPS_UTC_HOUR: ${get_gps_utc_hour()}
			GPS_UTC_MINUTE: ${get_gps_utc_minute()}
			GPS_UTC_SECOND: ${get_gps_utc_second()}
		""".trimIndent()
	}


	private fun getParam(o: Int, l: Int) : Int = CanBusNative.getECUParameterB(CanBAddrs.TELEAID_POS3, o, l)
}
