
package com.rndash.mbheadunit.nativeCan.canB

import com.rndash.mbheadunit.nativeCan.CanBusNative // AUTO GEN

/**
 *   Generated by db_converter.py
 *   Object for TELEAID_POS3 (ID 0x03E7)
**/

object TELEAID_POS3 {

    	/** Gets GPS date year UNIT: years **/
	fun get_gps_date_year() : Int = CanBusNative.getECUParameterB(CanBAddrs.TELEAID_POS3, 0, 16)
	
	/** Gets GPS date month UNIT: months **/
	fun get_gps_date_month() : Int = CanBusNative.getECUParameterB(CanBAddrs.TELEAID_POS3, 16, 8)
	
	/** Gets GPS date day UNIT: days **/
	fun get_gps_date_day() : Int = CanBusNative.getECUParameterB(CanBAddrs.TELEAID_POS3, 24, 8)
	
	/** Gets GPS UTC hour UNIT: h **/
	fun get_gps_utc_hour() : Int = CanBusNative.getECUParameterB(CanBAddrs.TELEAID_POS3, 32, 8)
	
	/** Gets GPS UTC minute UNIT: min **/
	fun get_gps_utc_minute() : Int = CanBusNative.getECUParameterB(CanBAddrs.TELEAID_POS3, 40, 8)
	
	/** Gets GPS UTC second UNIT: s **/
	fun get_gps_utc_second() : Int = CanBusNative.getECUParameterB(CanBAddrs.TELEAID_POS3, 48, 16)
	
	
}
