
package com.rndash.mbheadunit.nativeCan.canB

import com.rndash.mbheadunit.nativeCan.CanBusNative // AUTO GEN

/**
 *   Generated by db_converter.py
 *   Object for TELEAID_POS5 (ID 0x03E9)
**/

object TELEAID_POS5 {

    	/** Gets GPS visible satellites **/
	fun get_gps_vsbl_sat() : Int = CanBusNative.getECUParameterB(CanBAddrs.TELEAID_POS5, 4, 4)
	
	/** Gets GPS tracked satellites **/
	fun get_gps_trck_sat() : Int = CanBusNative.getECUParameterB(CanBAddrs.TELEAID_POS5, 0, 4)
	
	/** Gets GPS vertical dilution of position **/
	fun get_gps_vdop() : Int = CanBusNative.getECUParameterB(CanBAddrs.TELEAID_POS5, 8, 8)
	
	/** Gets GPS horizontal dilution of position **/
	fun get_gps_hdop() : Int = CanBusNative.getECUParameterB(CanBAddrs.TELEAID_POS5, 16, 8)
	
	/** Gets GPS dilution of position **/
	fun get_gps_pdop() : Int = CanBusNative.getECUParameterB(CanBAddrs.TELEAID_POS5, 24, 8)
	
	/** Gets GPS fix **/
	fun get_gps_fix() : GPS_FIX = when(CanBusNative.getECUParameterB(CanBAddrs.TELEAID_POS5, 36, 4)) {
		 0 -> GPS_FIX.RES
		 1 -> GPS_FIX.NAV
		 2 -> GPS_FIX.NO_FIX
		 3 -> GPS_FIX.FIX_2D
		 4 -> GPS_FIX.FIX_3D
		 else -> throw Exception("Invalid raw value for GPS_FIX")
	}
	
	/** Gets Dead reckoning / map matching position reliablity UNIT:% **/
	fun get_dr_mm_rel() : Int = CanBusNative.getECUParameterB(CanBAddrs.TELEAID_POS5, 40, 8)
	
	/** Gets Dead reckoning / map matching state **/
	fun get_dr_mm_stat() : DR_MM_STAT = when(CanBusNative.getECUParameterB(CanBAddrs.TELEAID_POS5, 54, 2)) {
		 0 -> DR_MM_STAT.NONE
		 1 -> DR_MM_STAT.DR
		 2 -> DR_MM_STAT.MM
		 3 -> DR_MM_STAT.SNA
		 else -> throw Exception("Invalid raw value for DR_MM_STAT")
	}
	
	/** Gets Map matching route state **/
	fun get_mm_route_stat() : MM_ROUTE_STAT = when(CanBusNative.getECUParameterB(CanBAddrs.TELEAID_POS5, 52, 2)) {
		 0 -> MM_ROUTE_STAT.ROUTE_OK
		 1 -> MM_ROUTE_STAT.NO_ROUTE
		 2 -> MM_ROUTE_STAT.NDEF
		 3 -> MM_ROUTE_STAT.SNA
		 else -> throw Exception("Invalid raw value for MM_ROUTE_STAT")
	}
	
	/** Gets Map matching road state **/
	fun get_mm_road_stat() : MM_ROAD_STAT = when(CanBusNative.getECUParameterB(CanBAddrs.TELEAID_POS5, 50, 2)) {
		 0 -> MM_ROAD_STAT.ON_RD
		 1 -> MM_ROAD_STAT.OFF_RD
		 2 -> MM_ROAD_STAT.NDEF
		 3 -> MM_ROAD_STAT.SNA
		 else -> throw Exception("Invalid raw value for MM_ROAD_STAT")
	}
	
	/** Gets Map matching map state **/
	fun get_mm_map_stat() : MM_MAP_STAT = when(CanBusNative.getECUParameterB(CanBAddrs.TELEAID_POS5, 48, 2)) {
		 0 -> MM_MAP_STAT.ON_MAP
		 1 -> MM_MAP_STAT.OFF_MAP
		 2 -> MM_MAP_STAT.NDEF
		 3 -> MM_MAP_STAT.SNA
		 else -> throw Exception("Invalid raw value for MM_MAP_STAT")
	}
	
	
}
