
package com.rndash.mbheadunit.nativeCan.canB

import com.rndash.mbheadunit.nativeCan.CanBusNative // AUTO GEN

/**
 *   Generated by db_converter.py
 *   Object for TELEAID_POS2 (ID 0x03E6)
**/

object TELEAID_POS2 {

    	/** Gets GPS velocity UNIT: cm / s **/
	fun get_gps_vel() : Int = CanBusNative.getECUParameterB(CanBAddrs.TELEAID_POS2, 0, 16)
	
	/** Gets GPS heading UNIT: ° **/
	fun get_gps_head() : Int = CanBusNative.getECUParameterB(CanBAddrs.TELEAID_POS2, 16, 16)
	
	/** Gets GPS ellipsoid height UNIT: m **/
	fun get_gps_ellip() : Int = CanBusNative.getECUParameterB(CanBAddrs.TELEAID_POS2, 32, 16)
	
	/** Gets GPS altitude UNIT: m **/
	fun get_gps_alt() : Int = CanBusNative.getECUParameterB(CanBAddrs.TELEAID_POS2, 48, 16)
	
	
}
