
@file:Suppress("unused", "FunctionName", "ClassName")
package com.rndash.mbheadunit.nativeCan.canB
import com.rndash.mbheadunit.CanFrame // AUTO GEN
import com.rndash.mbheadunit.nativeCan.CanBusNative // AUTO GEN

/**
 *   Generated by db_converter.py
 *   Object for TP_AGW_TELEAID6 (ID 0x03E3)
**/

object TP_AGW_TELEAID6 {

    /** 
     *  Returns the most recent Can Frame representing the state
     *  of TP_AGW_TELEAID6
    **/
    fun get_frame() : CanFrame? = CanBusNative.getBFrame(CanBAddrs.TP_AGW_TELEAID6)

	/** Gets communication AGW to TELEAID **/
	fun get_tp_agw_teleaid() : Int = CanBusNative.getECUParameterB(CanBAddrs.TP_AGW_TELEAID6, 0, 64)
	
	/** Sets communication AGW to TELEAID **/
	fun set_tp_agw_teleaid(f: CanFrame, p: Int) : CanFrame? {
		checkFrame(f)
		return CanBusNative.setFrameParameter(f, 0, 64, p)
	}
	
	/**
     * Auto generated function
     * Throws exception if user tries to set a value in a frame
     * Not designated from the correct ECU
    **/
    private fun checkFrame(f: CanFrame) {
        if (f.canID != CanBAddrs.TP_AGW_TELEAID6.addr) {
            throw IllegalArgumentException("CAN ID does not match object!")
        }
    }

	override fun toString() = """
		|Frame TP_AGW_TELEAID6 (0x03E3):
		|	communication AGW to TELEAID: ${get_tp_agw_teleaid()}
	""".trimMargin("|")
}
