
@file:Suppress("unused", "FunctionName", "ClassName")
package com.rndash.mbheadunit.nativeCan.canB
import com.rndash.mbheadunit.CanFrame // AUTO GEN
import com.rndash.mbheadunit.nativeCan.CanBusNative // AUTO GEN

/**
 *   Generated by db_converter.py
 *   Object for TP_KOMBI_TELEAID4 (ID 0x03E1)
**/

object TP_KOMBI_TELEAID4 {

    /** 
     *  Returns the most recent Can Frame representing the state
     *  of TP_KOMBI_TELEAID4
    **/
    fun get_frame() : CanFrame? = CanBusNative.getBFrame(CanBAddrs.TP_KOMBI_TELEAID4)

	/** Gets communication KOMBI to TELEAID **/
	fun get_tp_kombi_teleaid() : Int = CanBusNative.getECUParameterB(CanBAddrs.TP_KOMBI_TELEAID4, 0, 64)
	
	/** Sets communication KOMBI to TELEAID **/
	fun set_tp_kombi_teleaid(f: CanFrame, p: Int) {
		checkFrame(f)
		CanBusNative.setFrameParameter(f, 0, 64, p)
	}
	
	/**
     * Auto generated function
     * Throws exception if user tries to set a value in a frame
     * Not designated from the correct ECU
    **/
    private fun checkFrame(f: CanFrame) {
        if (f.canID != CanBAddrs.TP_KOMBI_TELEAID4.addr) {
            throw IllegalArgumentException("CAN ID does not match object!")
        }
    }

	override fun toString() = """
		|Frame TP_KOMBI_TELEAID4 (0x03E1):
		|	communication KOMBI to TELEAID: ${get_tp_kombi_teleaid()}
	""".trimMargin("|")
}
