
@file:Suppress("unused", "FunctionName", "ClassName")
package com.rndash.mbheadunit.nativeCan.canB
import com.rndash.mbheadunit.CanFrame // AUTO GEN
import com.rndash.mbheadunit.nativeCan.CanBusNative // AUTO GEN

/**
 *   Generated by db_converter.py
 *   Object for TP_MSS_AGW3 (ID 0x01D8)
**/

object TP_MSS_AGW3 {

    /** 
     *  Returns the most recent Can Frame representing the state
     *  of TP_MSS_AGW3
    **/
    fun get_frame() : CanFrame? = CanBusNative.getBFrame(CanBAddrs.TP_MSS_AGW3)

	/** Gets communication from the MSS to the AGW **/
	fun get_tp_mss_agw3() : Int = CanBusNative.getECUParameterB(CanBAddrs.TP_MSS_AGW3, 0, 64)
	
	/** Sets communication from the MSS to the AGW **/
	fun set_tp_mss_agw3(f: CanFrame, p: Int) : CanFrame? {
		checkFrame(f)
		return CanBusNative.setFrameParameter(f, 0, 64, p)
	}
	
	/**
     * Auto generated function
     * Throws exception if user tries to set a value in a frame
     * Not designated from the correct ECU
    **/
    private fun checkFrame(f: CanFrame) {
        if (f.canID != CanBAddrs.TP_MSS_AGW3.addr) {
            throw IllegalArgumentException("CAN ID does not match object!")
        }
    }

	override fun toString() = """
		|Frame TP_MSS_AGW3 (0x01D8):
		|	communication from the MSS to the AGW: ${get_tp_mss_agw3()}
	""".trimMargin("|")
}
