
@file:Suppress("unused", "FunctionName", "ClassName")
package com.rndash.mbheadunit.nativeCan.canB
import com.rndash.mbheadunit.CanFrame // AUTO GEN
import com.rndash.mbheadunit.nativeCan.CanBusNative // AUTO GEN

/**
 *   Generated by db_converter.py
 *   Object for TP_TELEAID_KOMBI4 (ID 0x01A1)
**/

object TP_TELEAID_KOMBI4 {

    /** 
     *  Returns the most recent Can Frame representing the state
     *  of TP_TELEAID_KOMBI4
    **/
    fun get_frame() : CanFrame? = CanBusNative.getBFrame(CanBAddrs.TP_TELEAID_KOMBI4)

	/** Gets Communication TELEAID to KOMBI **/
	fun get_tp_teleaid_kombi() : Int = CanBusNative.getECUParameterB(CanBAddrs.TP_TELEAID_KOMBI4, 0, 64)
	
	/** Sets Communication TELEAID to KOMBI **/
	fun set_tp_teleaid_kombi(f: CanFrame, p: Int) {
		checkFrame(f)
		CanBusNative.setFrameParameter(f, 0, 64, p)
	}
	
	/**
     * Auto generated function
     * Throws exception if user tries to set a value in a frame
     * Not designated from the correct ECU
    **/
    private fun checkFrame(f: CanFrame) {
        if (f.canID != CanBAddrs.TP_TELEAID_KOMBI4.addr) {
            throw IllegalArgumentException("CAN ID does not match object!")
        }
    }

	override fun toString() = """
		|Frame TP_TELEAID_KOMBI4 (0x01A1):
		|	Communication TELEAID to KOMBI: ${get_tp_teleaid_kombi()}
	""".trimMargin("|")
}
