package com.rndash.mbheadunit.nativeCan.canB


import com.rndash.mbheadunit.nativeCan.CanBAddrs
import com.rndash.mbheadunit.nativeCan.CanBusNative



/**
 *    GENERATED BY parse_kt.py
 *    Decoder class for ECU Frame TPM_A1 (ID: 0x02FF)
**/
object TPM_A1 {

	/** TPM message display request **/
	fun get_tpm_msgdisp_rq() : Int = getParam(0, 4)

	/** TPM state **/
	fun get_tpm_stat() : Int = getParam(4, 4)

	/** Tire pressure modules display on request **/
	fun get_tpm_disp_on_rq() : Boolean = getParam(9, 1) != 0

	/** Tire pressure module malfunction lamp on request **/
	fun get_tpm_malflmp_on_rq() : Boolean = getParam(10, 1) != 0

	/** Tire in limp-home operation mode **/
	fun get_tire_lhom() : Boolean = getParam(11, 1) != 0

	/** Tire pressure module indication lamp on request **/
	fun get_tpm_indlmp_on_rq() : Boolean = getParam(12, 1) != 0

	/** TPM warning display request **/
	fun get_tpm_warndisp_rq() : Int = getParam(13, 3)

	/** spare tire **/
	fun get_tire_spr() : Boolean = getParam(16, 1) != 0

	/** Tire rear right **/
	fun get_tire_rr() : Boolean = getParam(17, 1) != 0

	/** Tire rear left **/
	fun get_tire_rl() : Boolean = getParam(18, 1) != 0

	/** Tire front right **/
	fun get_tire_fr() : Boolean = getParam(19, 1) != 0

	/** Tire front left **/
	fun get_tire_fl() : Boolean = getParam(20, 1) != 0

	/** (bar) (Bar) Tire pressure front left **/
	fun get_tirepress_fl() : Int = getParam(24, 8)

	/** (bar) (Bar) Tire pressure front right **/
	fun get_tirepress_fr() : Int = getParam(32, 8)

	/** (bar) (Bar) Tire pressure left rear **/
	fun get_tirepress_rl() : Int = getParam(40, 8)

	/** (bar) (Bar) Tire pressure rear right **/
	fun get_tirepress_rr() : Int = getParam(48, 8)

	/** (bar) (Bar) Tire pressure spare tire **/
	fun get_tirepress_spr() : Int = getParam(56, 8)

	override fun toString(): String {
		return """
			TPM_MsgDisp_Rq: ${get_tpm_msgdisp_rq()}
			TPM_Stat: ${get_tpm_stat()}
			TPM_Disp_On_Rq: ${get_tpm_disp_on_rq()}
			TPM_MalfLmp_On_Rq: ${get_tpm_malflmp_on_rq()}
			Tire_LHOM: ${get_tire_lhom()}
			TPM_IndLmp_On_Rq: ${get_tpm_indlmp_on_rq()}
			TPM_WarnDisp_Rq: ${get_tpm_warndisp_rq()}
			Tire_Spr: ${get_tire_spr()}
			Tire_RR: ${get_tire_rr()}
			Tire_RL: ${get_tire_rl()}
			Tire_FR: ${get_tire_fr()}
			Tire_FL: ${get_tire_fl()}
			TirePress_FL: ${get_tirepress_fl()}
			TirePress_FR: ${get_tirepress_fr()}
			TirePress_RL: ${get_tirepress_rl()}
			TirePress_RR: ${get_tirepress_rr()}
			TirePress_Spr: ${get_tirepress_spr()}
		""".trimIndent()
	}


	private fun getParam(o: Int, l: Int) : Int = CanBusNative.getECUParameterB(CanBAddrs.TPM_A1, o, l)
}
