
package com.rndash.mbheadunit.nativeCan.canB

import com.rndash.mbheadunit.nativeCan.CanBusNative // AUTO GEN

/**
 *   Generated by db_converter.py
 *   Object for TVL_A1 (ID 0x028C)
**/

object TVL_A1 {

    	/** Gets seat front left **/
	fun get_svl_vor() : Boolean = CanBusNative.getECUParameterB(CanBAddrs.TVL_A1, 7, 1) != 0
	
	/** Gets seat front left **/
	fun get_svl_zur() : Boolean = CanBusNative.getECUParameterB(CanBAddrs.TVL_A1, 6, 1) != 0
	
	/** Gets seat front left **/
	fun get_svl_hi_auf() : Boolean = CanBusNative.getECUParameterB(CanBAddrs.TVL_A1, 5, 1) != 0
	
	/** Gets seat front left **/
	fun get_svl_hi_ab() : Boolean = CanBusNative.getECUParameterB(CanBAddrs.TVL_A1, 4, 1) != 0
	
	/** Gets front left seat **/
	fun get_svl_tgl() : Boolean = CanBusNative.getECUParameterB(CanBAddrs.TVL_A1, 0, 1) != 0
	
	/** Gets front left seat **/
	fun get_svl_le_vor() : Boolean = CanBusNative.getECUParameterB(CanBAddrs.TVL_A1, 13, 1) != 0
	
	/** Gets front left seat **/
	fun get_svl_le_zur() : Boolean = CanBusNative.getECUParameterB(CanBAddrs.TVL_A1, 12, 1) != 0
	
	/** Gets seat front left **/
	fun get_svl_vo_auf() : Boolean = CanBusNative.getECUParameterB(CanBAddrs.TVL_A1, 11, 1) != 0
	
	/** Gets seat front left **/
	fun get_svl_vo_ab() : Boolean = CanBusNative.getECUParameterB(CanBAddrs.TVL_A1, 10, 1) != 0
	
	/** Gets front left seat **/
	fun get_svl_kst_auf() : Boolean = CanBusNative.getECUParameterB(CanBAddrs.TVL_A1, 9, 1) != 0
	
	/** Gets front left seat **/
	fun get_svl_kst_ab() : Boolean = CanBusNative.getECUParameterB(CanBAddrs.TVL_A1, 8, 1) != 0
	
	/** Gets steering column up **/
	fun get_ls_auf_ll() : Boolean = CanBusNative.getECUParameterB(CanBAddrs.TVL_A1, 19, 1) != 0
	
	/** Gets steering column down **/
	fun get_ls_ab_ll() : Boolean = CanBusNative.getECUParameterB(CanBAddrs.TVL_A1, 18, 1) != 0
	
	/** Gets steering column forward **/
	fun get_ls_vor_ll() : Boolean = CanBusNative.getECUParameterB(CanBAddrs.TVL_A1, 17, 1) != 0
	
	/** Gets steering column to the rear (towards the driver) **/
	fun get_ls_zurueck_ll() : Boolean = CanBusNative.getECUParameterB(CanBAddrs.TVL_A1, 16, 1) != 0
	
	/** Gets memory front left **/
	fun get_mvl_p1_en() : Boolean = CanBusNative.getECUParameterB(CanBAddrs.TVL_A1, 31, 1) != 0
	
	/** Gets memory front left **/
	fun get_mvl_p2_en() : Boolean = CanBusNative.getECUParameterB(CanBAddrs.TVL_A1, 30, 1) != 0
	
	/** Gets memory front left **/
	fun get_mvl_p3_en() : Boolean = CanBusNative.getECUParameterB(CanBAddrs.TVL_A1, 29, 1) != 0
	
	/** Gets front left memory **/
	fun get_mvl_p1_sp() : Boolean = CanBusNative.getECUParameterB(CanBAddrs.TVL_A1, 28, 1) != 0
	
	/** Gets memory front left **/
	fun get_mvl_p2_sp() : Boolean = CanBusNative.getECUParameterB(CanBAddrs.TVL_A1, 27, 1) != 0
	
	/** Gets memory front left **/
	fun get_mvl_p3_sp() : Boolean = CanBusNative.getECUParameterB(CanBAddrs.TVL_A1, 26, 1) != 0
	
	/** Gets Save right outside mirror parking position **/
	fun get_spi_re_sp() : Boolean = CanBusNative.getECUParameterB(CanBAddrs.TVL_A1, 25, 1) != 0
	
	/** Gets front left memory **/
	fun get_mvl_tgl() : Boolean = CanBusNative.getECUParameterB(CanBAddrs.TVL_A1, 24, 1) != 0
	
	/** Gets outside mirror right to left (not 203) **/
	fun get_spi_re_n_li() : Boolean = CanBusNative.getECUParameterB(CanBAddrs.TVL_A1, 39, 1) != 0
	
	/** Gets Outside mirror right to right (not 203) **/
	fun get_spi_re_n_re() : Boolean = CanBusNative.getECUParameterB(CanBAddrs.TVL_A1, 38, 1) != 0
	
	/** Gets Outside mirror right up (not 203) **/
	fun get_spi_re_n_ob() : Boolean = CanBusNative.getECUParameterB(CanBAddrs.TVL_A1, 37, 1) != 0
	
	/** Gets Outside mirror right down (not 203) **/
	fun get_spi_re_n_un() : Boolean = CanBusNative.getECUParameterB(CanBAddrs.TVL_A1, 36, 1) != 0
	
	/** Gets Outside mirror right after garage position (not 203) **/
	fun get_spi_re_garage() : Boolean = CanBusNative.getECUParameterB(CanBAddrs.TVL_A1, 35, 1) != 0
	
	/** Gets Outside mirror right after driving position (not 203) **/
	fun get_spi_re_fahren() : Boolean = CanBusNative.getECUParameterB(CanBAddrs.TVL_A1, 34, 1) != 0
	
	/** Gets Mirror adjustment switch actuated **/
	fun get_spvs_bet_ll() : Boolean = CanBusNative.getECUParameterB(CanBAddrs.TVL_A1, 32, 1) != 0
	
	
}
