package com.rndash.mbheadunit.nativeCan.canB


import com.rndash.mbheadunit.nativeCan.CanBAddrs
import com.rndash.mbheadunit.nativeCan.CanBusNative



/**
 *    GENERATED BY parse_kt.py
 *    Decoder class for ECU Frame TVL_A4 (ID: 0x00E8)
**/
object TVL_A4 {

	/** Code Zugangberechtigung **/
	fun get_zbc_tvl() : Int = getParam(0, 64)

	override fun toString(): String {
		return """
			ZBC_TVL: ${get_zbc_tvl()}
		""".trimIndent()
	}


	private fun getParam(o: Int, l: Int) : Int = CanBusNative.getECUParameterB(CanBAddrs.TVL_A4, o, l)
}
