package com.rndash.mbheadunit.nativeCan.canB


import com.rndash.mbheadunit.nativeCan.CanBAddrs
import com.rndash.mbheadunit.nativeCan.CanBusNative



/**
 *    GENERATED BY parse_kt.py
 *    Decoder class for ECU Frame TVL_A2 (ID: 0x0044)
**/
object TVL_A2 {

	/** rear window open / close right **/
	fun get_fhr_tvl() : Boolean = getParam(8, 1) != 0

	/** Open windows, rear left / Close **/
	fun get_fhl_tvl() : Boolean = getParam(9, 1) != 0

	/** Front windows open / close right **/
	fun get_fvr_tvl() : Boolean = getParam(10, 1) != 0

	/** Open windows front left / Close **/
	fun get_fvl_tvl() : Boolean = getParam(11, 1) != 0

	/** Open / close SHD / top **/
	fun get_shd_tvl() : Boolean = getParam(12, 1) != 0

	/** Direction touch control **/
	fun get_kb_ri_tvl() : Boolean = getParam(13, 1) != 0

	/** Mode-touch control **/
	fun get_kb_mod_tvl() : Boolean = getParam(14, 1) != 0

	/** automatically close **/
	fun get_fhr_as_ll() : Boolean = getParam(16, 1) != 0

	/** manually close **/
	fun get_fhr_ms_ll() : Boolean = getParam(17, 1) != 0

	/** manually open **/
	fun get_fhr_moe_ll() : Boolean = getParam(18, 1) != 0

	/** Automatically open **/
	fun get_fhr_aoe_ll() : Boolean = getParam(19, 1) != 0

	/** Left rear windows **/
	fun get_fhl_as_ll() : Boolean = getParam(20, 1) != 0

	/** rear left window **/
	fun get_fhl_ms_ll() : Boolean = getParam(21, 1) != 0

	/** Left rear window **/
	fun get_fhl_moe_ll() : Boolean = getParam(22, 1) != 0

	/** Left rear windows **/
	fun get_fhl_aoe_ll() : Boolean = getParam(23, 1) != 0

	/** automatically close **/
	fun get_fvr_as() : Boolean = getParam(24, 1) != 0

	/** manually close **/
	fun get_fvr_ms() : Boolean = getParam(25, 1) != 0

	/** manually open **/
	fun get_fvr_moe() : Boolean = getParam(26, 1) != 0

	/** Automatically Open **/
	fun get_fvr_aoe() : Boolean = getParam(27, 1) != 0

	override fun toString(): String {
		return """
			FHR_TVL: ${get_fhr_tvl()}
			FHL_TVL: ${get_fhl_tvl()}
			FVR_TVL: ${get_fvr_tvl()}
			FVL_TVL: ${get_fvl_tvl()}
			SHD_TVL: ${get_shd_tvl()}
			KB_RI_TVL: ${get_kb_ri_tvl()}
			KB_MOD_TVL: ${get_kb_mod_tvl()}
			FHR_AS_LL: ${get_fhr_as_ll()}
			FHR_MS_LL: ${get_fhr_ms_ll()}
			FHR_MOE_LL: ${get_fhr_moe_ll()}
			FHR_AOE_LL: ${get_fhr_aoe_ll()}
			FHL_AS_LL: ${get_fhl_as_ll()}
			FHL_MS_LL: ${get_fhl_ms_ll()}
			FHL_MOE_LL: ${get_fhl_moe_ll()}
			FHL_AOE_LL: ${get_fhl_aoe_ll()}
			FVR_AS: ${get_fvr_as()}
			FVR_MS: ${get_fvr_ms()}
			FVR_MOE: ${get_fvr_moe()}
			FVR_AOE: ${get_fvr_aoe()}
		""".trimIndent()
	}


	private fun getParam(o: Int, l: Int) : Int = CanBusNative.getECUParameterB(CanBAddrs.TVL_A2, o, l)
}
