package com.rndash.mbheadunit.nativeCan.canB


import com.rndash.mbheadunit.nativeCan.CanBAddrs
import com.rndash.mbheadunit.nativeCan.CanBusNative



/**
 *    GENERATED BY parse_kt.py
 *    Decoder class for ECU Frame TVR_A4 (ID: 0x00EC)
**/
object TVR_A4 {

	/** Code Zugangberechtigung **/
	fun get_zbc_tvr() : Int = getParam(0, 64)

	override fun toString(): String {
		return """
			ZBC_TVR: ${get_zbc_tvr()}
		""".trimIndent()
	}


	private fun getParam(o: Int, l: Int) : Int = CanBusNative.getECUParameterB(CanBAddrs.TVR_A4, o, l)
}
