
package com.rndash.mbheadunit.nativeCan.canB

import com.rndash.mbheadunit.nativeCan.CanBusNative // AUTO GEN

/**
 *   Generated by db_converter.py
 *   Object for TVR_A4 (ID 0x00EC)
**/

object TVR_A4 {

    	/** Gets Access authorization code **/
	fun get_zbc_tvr() : Int = CanBusNative.getECUParameterB(CanBAddrs.TVR_A4, 0, 64)
	
	
}
